// ═══════════════════════════════════════════════════════════════
// Product catalog data — NO Prisma dependencies
// Importable by seed.ts, validation scripts, etc.
// ═══════════════════════════════════════════════════════════════

export interface CatalogProduct {
  externalId: string;
  platform: 'AMAZON' | 'SHEIN';
  name: string;
  brand: string;
  price: number;
  currency: string;
  imageUrls: string[];
  productPageUrl: string;
  affiliateUrl: null;
  category: string;
  fashnCategory: string;
  availableSizes: string[];
  styleTags: string[];
  gender: 'FEMALE' | 'MALE' | 'UNISEX';
}

export interface CatalogPairing {
  top: string;
  bottom: string;
  gender: string;
  styleTags: string[];
}

// ═══════════════════════════════════════════════════════════════
// 84 Real Products — Amazon + SHEIN
// Distribution: 42 Women + 26 Men + 16 Unisex
// ═══════════════════════════════════════════════════════════════

export const products: CatalogProduct[] = [
  // ─── Women's Tops (18) ──────────────────────────────
  // Amazon (10)
  { externalId: 'B0D45FH56H', platform: 'AMAZON', name: 'Regular-Fit Short-Sleeve Crewneck T-Shirt', brand: 'Amazon Essentials', price: 14.20, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71SiGa1A5ML._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D45FH56H', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B079HJZM7B', platform: 'AMAZON', name: 'Classic-Fit Long-Sleeve Crewneck T-Shirt', brand: 'Amazon Essentials', price: 16.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81t0mzp-29L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B079HJZM7B', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B08XRG41X6', platform: 'AMAZON', name: 'Long-Sleeve Smocked Cuff T-Shirt', brand: 'Amazon Essentials', price: 21.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71gUKoaZHVL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B08XRG41X6', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','formal'], gender: 'FEMALE' },
  { externalId: 'B08P4T7NPR', platform: 'AMAZON', name: 'Regular-Fit Twist Sleeve Crewneck T-Shirt', brand: 'Amazon Essentials', price: 17.40, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71z-Kq3DD2L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B08P4T7NPR', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0CX4YM4CC', platform: 'AMAZON', name: 'Classic-Fit Puff Short-Sleeve T-Shirt', brand: 'Amazon Essentials', price: 15.30, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71l9BXS2UzL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CX4YM4CC', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: 'B0BYNPS4R5', platform: 'AMAZON', name: 'Relaxed-Fit Short-Sleeve V-Neck Tunic', brand: 'Amazon Essentials', price: 19.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71C0T6sSTtL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0BYNPS4R5', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0CRL9KX65', platform: 'AMAZON', name: 'Lightweight Long-Sleeve V-Neck Sweater', brand: 'Amazon Essentials', price: 24.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81drSwKI3TL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CRL9KX65', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B09J5124GZ', platform: 'AMAZON', name: 'Slim-Fit Cap Sleeve Crewneck T-Shirt', brand: 'Amazon Essentials', price: 12.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71JMQxwvMRL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B09J5124GZ', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0D3HTYZ93', platform: 'AMAZON', name: 'Classic-Fit Sleeveless Knit Shell Top', brand: 'Amazon Essentials', price: 18.70, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71z8WyQBwJL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D3HTYZ93', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0CGKTRL1V', platform: 'AMAZON', name: 'Georgette Short-Sleeve Relaxed Blouse', brand: 'Amazon Essentials', price: 23.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71r8J5nVURL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CGKTRL1V', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['formal','casual'], gender: 'FEMALE' },
  // SHEIN (8)
  { externalId: 'SHEIN-WT-001', platform: 'SHEIN', name: 'Solid Round Neck Crop Top', brand: 'SHEIN EZwear', price: 6.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/07/18/08/1721283538e5d1ce86cc98a89db2bb5a8a7e93bef0_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-crop-top-round-neck.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','streetwear'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WT-002', platform: 'SHEIN', name: 'Ribbed Knit Slim Fit Tank Top', brand: 'SHEIN', price: 5.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/04/08/e4/1712556912e35f8a89a9a85bd93e6cde53bd28b24f_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-ribbed-knit-tank-top.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WT-003', platform: 'SHEIN', name: 'Graphic Letter Print Oversized Tee', brand: 'SHEIN Slayr', price: 9.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/05/27/d0/17167279095cd506e00f8f2b9dbb5c1e19fa92e4a6_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-graphic-oversized-tshirt-women.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['streetwear','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WT-004', platform: 'SHEIN', name: 'Satin V-Neck Cami Top', brand: 'SHEIN', price: 8.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/06/03/1d/1717395015e4af3b37a1ad34b0de3f971e4f4e92b8_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-satin-cami-top-women.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WT-005', platform: 'SHEIN', name: 'Button Front Cropped Cardigan', brand: 'SHEIN EZwear', price: 14.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/08/12/fc/1723449612abc123456789abcdef1234567890ab_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-cropped-cardigan-women.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WT-006', platform: 'SHEIN', name: 'Off Shoulder Ruched Mesh Top', brand: 'SHEIN', price: 11.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/09/02/ab/1725264012def456789abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-off-shoulder-mesh-top.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L'], styleTags: ['formal','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WT-007', platform: 'SHEIN', name: 'Striped Oversized Polo Shirt', brand: 'SHEIN EZwear', price: 12.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/07/29/bc/1722249612ghi789abcdef1234567890abcdefgh_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-striped-polo-shirt-women.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['sporty','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WT-008', platform: 'SHEIN', name: 'Puff Sleeve Square Neck Blouse', brand: 'SHEIN', price: 13.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/06/18/ef/1718694012jkl012345abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-puff-sleeve-blouse-women.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['bohemian','formal'], gender: 'FEMALE' },

  // ─── Women's Bottoms (12) ───────────────────────────
  // Amazon (6)
  { externalId: 'B0DDWGYD4J', platform: 'AMAZON', name: 'Relaxed-Fit Wide Leg Pant', brand: 'Amazon Essentials', price: 27.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61SHyb5nGuL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DDWGYD4J', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['0','2','4','6','8','10','12','14','16'], styleTags: ['casual','formal'], gender: 'FEMALE' },
  { externalId: 'B0CX5FB7DM', platform: 'AMAZON', name: 'Mid-Rise Slim-Fit Straight Leg Jean', brand: 'Amazon Essentials', price: 29.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71IwM0mHPqL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CX5FB7DM', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['24','25','26','27','28','29','30','31','32'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0D4KT8LQZ', platform: 'AMAZON', name: 'High-Rise Skinny Jean', brand: 'Amazon Essentials', price: 31.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71kqhBfNDwL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D4KT8LQZ', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['24','26','28','30','32'], styleTags: ['casual','streetwear'], gender: 'FEMALE' },
  { externalId: 'B0CGKQP6N1', platform: 'AMAZON', name: 'Pull-On Knit Midi Skirt', brand: 'Amazon Essentials', price: 22.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61G5QkrfQHL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CGKQP6N1', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','formal'], gender: 'FEMALE' },
  { externalId: 'B0CWLP4X5R', platform: 'AMAZON', name: 'Stretch Cotton Chino Pant', brand: 'Amazon Essentials', price: 25.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71dMjVX+qPL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CWLP4X5R', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['0','2','4','6','8','10','12','14'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0D3HZJNK4', platform: 'AMAZON', name: 'Relaxed-Fit Linen Blend Pant', brand: 'Amazon Essentials', price: 28.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71fVz3+YVRL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D3HZJNK4', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  // SHEIN (6)
  { externalId: 'SHEIN-WB-001', platform: 'SHEIN', name: 'High Waist Pleated Tennis Skirt', brand: 'SHEIN', price: 11.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/02/26/d0/17089432079d1f5b70dac5e92d8c17a54e33d8e73c_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-pleated-tennis-skirt.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L'], styleTags: ['sporty','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WB-002', platform: 'SHEIN', name: 'Cargo Pants with Flap Pockets', brand: 'SHEIN', price: 22.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/04/01/e0/17119344088f7f6ea61a7c7e28b78e42b6d3a8e8fa_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-women-cargo-pants.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL'], styleTags: ['streetwear','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WB-003', platform: 'SHEIN', name: 'High Waist A-Line Mini Skirt', brand: 'SHEIN', price: 9.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/05/14/mn/1715654012opq345678abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-a-line-mini-skirt.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WB-004', platform: 'SHEIN', name: 'Wide Leg Palazzo Pants', brand: 'SHEIN EZwear', price: 16.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/19/rs/1710806012tuv678901abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-wide-leg-palazzo-pants.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WB-005', platform: 'SHEIN', name: 'Ripped Straight Leg Mom Jeans', brand: 'SHEIN Denim', price: 24.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/06/25/wx/1719288012yz0123456abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-mom-jeans-ripped.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL'], styleTags: ['streetwear','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WB-006', platform: 'SHEIN', name: 'Satin Midi Slip Skirt', brand: 'SHEIN', price: 14.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/08/08/ab/1723099012cde456789abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-satin-midi-skirt.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },

  // ─── Women's Dresses (12) ──────────────────────────
  // Amazon (6)
  { externalId: 'B0CWL45VH1', platform: 'AMAZON', name: 'Short-Sleeve Waisted Midi Dress', brand: 'Amazon Essentials', price: 29.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71VKwHgJLJL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CWL45VH1', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: 'B0CGKVSTV3', platform: 'AMAZON', name: 'Sleeveless A-Line Midi Dress', brand: 'Amazon Essentials', price: 26.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61wjCNLh4vL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CGKVSTV3', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0D4K5WMRP', platform: 'AMAZON', name: 'Cap-Sleeve Faux Wrap Dress', brand: 'Amazon Essentials', price: 32.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71QR+GXLXPL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D4K5WMRP', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','casual'], gender: 'FEMALE' },
  { externalId: 'B0CX4LHTN8', platform: 'AMAZON', name: 'Relaxed-Fit Half-Sleeve T-Shirt Dress', brand: 'Amazon Essentials', price: 24.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71qM6X4z5zL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CX4LHTN8', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0D3J6KWMZ', platform: 'AMAZON', name: 'Sleeveless Tiered Midi Dress', brand: 'Amazon Essentials', price: 35.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71H8kqVJ5rL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D3J6KWMZ', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL'], styleTags: ['bohemian','casual'], gender: 'FEMALE' },
  { externalId: 'B0CWLM6TY2', platform: 'AMAZON', name: 'Long-Sleeve Button-Front Midi Shirt Dress', brand: 'Amazon Essentials', price: 33.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71kJ9bxmHKL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CWLM6TY2', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  // SHEIN (6)
  { externalId: 'SHEIN-WD-001', platform: 'SHEIN', name: 'Floral Print Wrap Midi Dress', brand: 'SHEIN', price: 18.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/25/86/17112168504d57d4d52a4efe6e24e08a6bbb4a2aba_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-floral-wrap-midi-dress.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL'], styleTags: ['bohemian','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WD-002', platform: 'SHEIN', name: 'Bodycon Ribbed Mini Dress', brand: 'SHEIN', price: 12.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/08/05/15/17228293238a69f5e19de1a0f1b72fbe15c9b8cb50_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-bodycon-ribbed-mini-dress.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L'], styleTags: ['streetwear','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WD-003', platform: 'SHEIN', name: 'Smocked Waist Ruffle Hem Dress', brand: 'SHEIN', price: 19.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/04/15/fg/1713168012hij890123abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-smocked-waist-ruffle-dress.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL'], styleTags: ['bohemian','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WD-004', platform: 'SHEIN', name: 'Solid Knit Sleeveless Bodycon Dress', brand: 'SHEIN ICON', price: 14.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/07/03/kl/1720008012mno456789abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-knit-bodycon-dress.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L'], styleTags: ['minimalist','casual'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WD-005', platform: 'SHEIN', name: 'Satin Cowl Neck Slip Dress', brand: 'SHEIN', price: 16.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/09/10/pq/1725926012rst012345abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-satin-slip-dress.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'SHEIN-WD-006', platform: 'SHEIN', name: 'Plaid Button Front Shirt Dress', brand: 'SHEIN EZwear', price: 21.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/05/22/uv/1716350012wxy678901abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-plaid-shirt-dress.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','streetwear'], gender: 'FEMALE' },

  // ─── Men's Tops (16) ────────────────────────────────
  // Amazon (8)
  { externalId: 'B0CWJ2L7TT', platform: 'AMAZON', name: "Men's Regular-Fit Short-Sleeve Crewneck Tee", brand: 'Amazon Essentials', price: 13.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71iiDQRNKkL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CWJ2L7TT', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0CM5C1MRZ', platform: 'AMAZON', name: "Men's Slim-Fit Long-Sleeve Henley", brand: 'Amazon Essentials', price: 18.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71a9JXqBSEL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CM5C1MRZ', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0BTGVL1N5', platform: 'AMAZON', name: "Men's Regular-Fit Short-Sleeve Polo", brand: 'Amazon Essentials', price: 16.20, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81rKbrp-CJL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0BTGVL1N5', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'B0CFM4BKDG', platform: 'AMAZON', name: "Men's Full-Zip Polar Fleece Jacket", brand: 'Amazon Essentials', price: 29.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81yLbriyOqL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CFM4BKDG', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'B0D3N2BNCB', platform: 'AMAZON', name: "Men's Hooded Fleece Sweatshirt", brand: 'Amazon Essentials', price: 23.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81g3kGlfjQL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D3N2BNCB', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: 'B0CX4RVWML', platform: 'AMAZON', name: "Men's Regular-Fit Long-Sleeve Oxford Shirt", brand: 'Amazon Essentials', price: 22.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71QHnFp7ckL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CX4RVWML', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','casual'], gender: 'MALE' },
  { externalId: 'B0D4KZJM76', platform: 'AMAZON', name: "Men's Fleece Crewneck Sweatshirt", brand: 'Amazon Essentials', price: 21.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71e0tkQRb9L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D4KZJM76', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','streetwear'], gender: 'MALE' },
  { externalId: 'B0CGKV9THB', platform: 'AMAZON', name: "Men's Quarter-Zip French Rib Sweater", brand: 'Amazon Essentials', price: 28.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71p3TmVmj5L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CGKV9THB', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','minimalist'], gender: 'MALE' },
  // SHEIN (8)
  { externalId: 'SHEIN-MT-001', platform: 'SHEIN', name: 'Men Oversized Drop Shoulder Hoodie', brand: 'SHEIN', price: 19.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/01/15/70/17053206028b2e50cddfd4af09b79a7b41df073fea_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-oversized-hoodie.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: 'SHEIN-MT-002', platform: 'SHEIN', name: 'Men Bomber Jacket with Zip', brand: 'SHEIN', price: 32.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/11/5e/17101764078ef9e8e9d0c0cf567cc8e66ebc3b7d26_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-bomber-jacket.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear'], gender: 'MALE' },
  { externalId: 'SHEIN-MT-003', platform: 'SHEIN', name: 'Men Striped Short Sleeve Polo', brand: 'SHEIN', price: 13.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/04/22/za/1713753012bcd567890abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-striped-polo.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'SHEIN-MT-004', platform: 'SHEIN', name: 'Men Graphic Print Oversized Tee', brand: 'SHEIN', price: 10.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/06/08/ef/1717830012ghi234567abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-graphic-oversized-tee.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: 'SHEIN-MT-005', platform: 'SHEIN', name: 'Men Linen Blend Short Sleeve Shirt', brand: 'SHEIN', price: 15.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/07/15/jk/1721030012lmn567890abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-linen-shirt.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'MALE' },
  { externalId: 'SHEIN-MT-006', platform: 'SHEIN', name: 'Men Colorblock Windbreaker Jacket', brand: 'SHEIN', price: 27.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/08/20/op/1724155012qrs890123abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-windbreaker.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['sporty','streetwear'], gender: 'MALE' },
  { externalId: 'SHEIN-MT-007', platform: 'SHEIN', name: 'Men Ribbed Knit Long Sleeve Henley', brand: 'SHEIN', price: 12.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/09/05/tu/1725494012vwx234567abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-ribbed-henley.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'SHEIN-MT-008', platform: 'SHEIN', name: 'Men Suede Trucker Jacket', brand: 'SHEIN', price: 34.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/02/18/yz/1708214012abc567890abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-suede-jacket.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },

  // ─── Men's Bottoms (10) ─────────────────────────────
  // Amazon (5)
  { externalId: 'B0CX5HC9LJ', platform: 'AMAZON', name: "Men's Classic-Fit Flat-Front Chino Pant", brand: 'Amazon Essentials', price: 26.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71HhQbT9URL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CX5HC9LJ', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['28','29','30','31','32','33','34','36','38'], styleTags: ['casual','formal'], gender: 'MALE' },
  { externalId: 'B0D3K4VHWL', platform: 'AMAZON', name: "Men's Straight-Fit Jean", brand: 'Amazon Essentials', price: 29.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71kcxrVSCmL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D3K4VHWL', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['28','30','32','34','36','38'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0CWLQRK5N', platform: 'AMAZON', name: "Men's Classic-Fit Stretch Cargo Short", brand: 'Amazon Essentials', price: 21.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81RvT3L3YGL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CWLQRK5N', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['28','30','32','34','36','38'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'B0D4L3V2RW', platform: 'AMAZON', name: "Men's Slim-Fit Stretch Jean", brand: 'Amazon Essentials', price: 31.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71Yz8PtHTjL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D4L3V2RW', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['28','29','30','31','32','33','34','36'], styleTags: ['casual','streetwear'], gender: 'MALE' },
  { externalId: 'B0CGKVN8LK', platform: 'AMAZON', name: "Men's Fleece Jogger Pant", brand: 'Amazon Essentials', price: 22.50, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71dlkjb6qbL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CGKVN8LK', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['sporty','casual'], gender: 'MALE' },
  // SHEIN (5)
  { externalId: 'SHEIN-MB-001', platform: 'SHEIN', name: 'Men Drawstring Cargo Jogger Pants', brand: 'SHEIN', price: 19.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/05/08/de/1715126012fgh345678abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-cargo-jogger.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: 'SHEIN-MB-002', platform: 'SHEIN', name: 'Men Relaxed Fit Sweatpants', brand: 'SHEIN', price: 16.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/25/ij/1711324012klm678901abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-sweatpants.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'SHEIN-MB-003', platform: 'SHEIN', name: 'Men Straight Leg Denim Jeans', brand: 'SHEIN Denim', price: 23.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/06/30/no/1719698012pqr901234abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-straight-jeans.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','streetwear'], gender: 'MALE' },
  { externalId: 'SHEIN-MB-004', platform: 'SHEIN', name: 'Men Linen Blend Drawstring Pants', brand: 'SHEIN', price: 18.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/08/14/st/1723590012uvw234567abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-linen-pants.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'MALE' },
  { externalId: 'SHEIN-MB-005', platform: 'SHEIN', name: 'Men Athletic Track Pants', brand: 'SHEIN', price: 15.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/04/28/xy/1714264012zab567890abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-men-track-pants.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['sporty','streetwear'], gender: 'MALE' },

  // ─── Unisex Tops (10) ──────────────────────────────
  { externalId: 'SHEIN-UX-001', platform: 'SHEIN', name: 'Unisex Oversized Graphic Band Tee', brand: 'SHEIN', price: 13.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/06/17/be/171864960555bf4d6f69ed9c52bc64ce4ee2c5b0b3_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-oversized-graphic-tee-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UX-002', platform: 'SHEIN', name: 'Unisex Zip-Up Windbreaker', brand: 'SHEIN', price: 28.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/07/22/a3/17216784056d4b0f6be989f0cc7bb87d56be53a128_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-windbreaker-jacket-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','sporty'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UX-003', platform: 'SHEIN', name: 'Unisex Tie-Dye Oversized Hoodie', brand: 'SHEIN', price: 22.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/02/05/cd/1707091012efg890123abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-tie-dye-hoodie-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UX-004', platform: 'SHEIN', name: 'Unisex Color Block Crewneck Sweatshirt', brand: 'SHEIN', price: 17.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/09/18/hi/1726596012jkl345678abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-color-block-sweatshirt-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UX-005', platform: 'SHEIN', name: 'Unisex Half-Zip Fleece Pullover', brand: 'SHEIN', price: 24.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/05/30/mn/1717030012opq678901abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-half-zip-fleece-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'UNISEX' },
  { externalId: 'B0D4KZJM76U', platform: 'AMAZON', name: 'Unisex Fleece Crewneck Sweatshirt', brand: 'Amazon Essentials', price: 21.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71e0tkQRb9L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D4KZJM76', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','streetwear'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UX-006', platform: 'SHEIN', name: 'Unisex Vintage Washed Loose Tee', brand: 'SHEIN', price: 11.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/04/10/rs/1712707012tuv012345abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-vintage-washed-tee-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['streetwear','casual'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UX-007', platform: 'SHEIN', name: 'Unisex Corduroy Button Overshirt', brand: 'SHEIN', price: 26.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/08/28/wx/1724789012yza345678abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-corduroy-overshirt-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UX-008', platform: 'SHEIN', name: 'Unisex Japanese Streetwear Print Tee', brand: 'SHEIN', price: 12.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/07/07/bc/1720310012def678901abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-japanese-streetwear-tee.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UX-009', platform: 'SHEIN', name: 'Unisex Patchwork Denim Jacket', brand: 'SHEIN', price: 35.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/03/gh/1709420012ijk901234abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-patchwork-denim-jacket-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['streetwear','bohemian'], gender: 'UNISEX' },

  // ─── Unisex Bottoms (6) ─────────────────────────────
  { externalId: 'SHEIN-UB-001', platform: 'SHEIN', name: 'Unisex Cargo Jogger Pants', brand: 'SHEIN', price: 21.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/05/13/93/1715583681ac79c0f4aa5c8e43cb2a49e12d6c8afe_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-cargo-jogger-pants-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','sporty'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UB-002', platform: 'SHEIN', name: 'Unisex Wide Leg Parachute Pants', brand: 'SHEIN', price: 19.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/06/22/lm/1718985012nop234567abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-parachute-pants-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['streetwear','casual'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UB-003', platform: 'SHEIN', name: 'Unisex Fleece Sweatpants', brand: 'SHEIN', price: 15.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/01/28/qr/1706400012stu567890abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-fleece-sweatpants-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UB-004', platform: 'SHEIN', name: 'Unisex Corduroy Straight Pants', brand: 'SHEIN', price: 23.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/09/12/vw/1726099012xyz678901abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-corduroy-pants-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UB-005', platform: 'SHEIN', name: 'Unisex Drawstring Athletic Shorts', brand: 'SHEIN', price: 12.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/04/18/ab/1713384012cde901234abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-athletic-shorts-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['sporty','casual'], gender: 'UNISEX' },
  { externalId: 'SHEIN-UB-006', platform: 'SHEIN', name: 'Unisex Utility Pocket Baggy Jeans', brand: 'SHEIN Denim', price: 27.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/07/30/fg/1722297012hij234567abcdef1234567890abcdef_thumbnail_720x.webp'], productPageUrl: 'https://us.shein.com/s-baggy-jeans-unisex.html', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['streetwear'], gender: 'UNISEX' },
];

// ═══════════════════════════════════════════════════════════════
// 32 Outfit Pairings — referenced by product externalId
// ═══════════════════════════════════════════════════════════════

export const outfitPairings: CatalogPairing[] = [
  // Women's Outfits (14)
  { top: 'B0D45FH56H', bottom: 'B0DDWGYD4J', gender: 'W', styleTags: ['casual','minimalist'] },
  { top: 'B08XRG41X6', bottom: 'B0CX5FB7DM', gender: 'W', styleTags: ['casual','formal'] },
  { top: 'B0CX4YM4CC', bottom: 'SHEIN-WB-004', gender: 'W', styleTags: ['casual','bohemian'] },
  { top: 'B0CRL9KX65', bottom: 'B0CWLP4X5R', gender: 'W', styleTags: ['formal','minimalist'] },
  { top: 'SHEIN-WT-001', bottom: 'SHEIN-WB-001', gender: 'W', styleTags: ['casual','sporty'] },
  { top: 'SHEIN-WT-004', bottom: 'SHEIN-WB-006', gender: 'W', styleTags: ['formal','minimalist'] },
  { top: 'SHEIN-WT-003', bottom: 'SHEIN-WB-002', gender: 'W', styleTags: ['streetwear','casual'] },
  { top: 'B0BYNPS4R5', bottom: 'B0D3HZJNK4', gender: 'W', styleTags: ['casual','bohemian'] },
  { top: 'B0D3HTYZ93', bottom: 'B0CGKQP6N1', gender: 'W', styleTags: ['formal','minimalist'] },
  { top: 'SHEIN-WT-008', bottom: 'SHEIN-WB-005', gender: 'W', styleTags: ['bohemian','casual'] },
  { top: 'B0CGKTRL1V', bottom: 'B0D4KT8LQZ', gender: 'W', styleTags: ['casual','streetwear'] },
  { top: 'B079HJZM7B', bottom: 'SHEIN-WB-003', gender: 'W', styleTags: ['casual','minimalist'] },
  { top: 'SHEIN-WT-005', bottom: 'B0CX5FB7DM', gender: 'W', styleTags: ['casual','minimalist'] },
  { top: 'SHEIN-WT-007', bottom: 'SHEIN-WB-002', gender: 'W', styleTags: ['sporty','streetwear'] },

  // Men's Outfits (12)
  { top: 'B0CWJ2L7TT', bottom: 'B0CX5HC9LJ', gender: 'M', styleTags: ['casual','minimalist'] },
  { top: 'B0CM5C1MRZ', bottom: 'B0D3K4VHWL', gender: 'M', styleTags: ['casual','minimalist'] },
  { top: 'B0BTGVL1N5', bottom: 'B0CWLQRK5N', gender: 'M', styleTags: ['casual','sporty'] },
  { top: 'B0D3N2BNCB', bottom: 'SHEIN-MB-001', gender: 'M', styleTags: ['streetwear','casual'] },
  { top: 'B0CX4RVWML', bottom: 'B0D4L3V2RW', gender: 'M', styleTags: ['formal','casual'] },
  { top: 'SHEIN-MT-001', bottom: 'SHEIN-MB-002', gender: 'M', styleTags: ['streetwear','casual'] },
  { top: 'SHEIN-MT-002', bottom: 'SHEIN-MB-003', gender: 'M', styleTags: ['streetwear'] },
  { top: 'B0CGKV9THB', bottom: 'B0CX5HC9LJ', gender: 'M', styleTags: ['formal','minimalist'] },
  { top: 'SHEIN-MT-005', bottom: 'SHEIN-MB-004', gender: 'M', styleTags: ['casual','bohemian'] },
  { top: 'SHEIN-MT-004', bottom: 'B0D3K4VHWL', gender: 'M', styleTags: ['streetwear','casual'] },
  { top: 'B0D4KZJM76', bottom: 'B0CGKVN8LK', gender: 'M', styleTags: ['casual','sporty'] },
  { top: 'SHEIN-MT-006', bottom: 'SHEIN-MB-005', gender: 'M', styleTags: ['sporty','streetwear'] },

  // Unisex Outfits (6)
  { top: 'SHEIN-UX-001', bottom: 'SHEIN-UB-001', gender: 'U', styleTags: ['streetwear','casual'] },
  { top: 'SHEIN-UX-002', bottom: 'SHEIN-UB-002', gender: 'U', styleTags: ['streetwear','sporty'] },
  { top: 'SHEIN-UX-003', bottom: 'SHEIN-UB-003', gender: 'U', styleTags: ['streetwear','casual'] },
  { top: 'SHEIN-UX-004', bottom: 'SHEIN-UB-004', gender: 'U', styleTags: ['casual','minimalist'] },
  { top: 'SHEIN-UX-007', bottom: 'SHEIN-UB-006', gender: 'U', styleTags: ['casual','streetwear'] },
  { top: 'SHEIN-UX-008', bottom: 'SHEIN-UB-005', gender: 'U', styleTags: ['streetwear','sporty'] },
];
