// ═══════════════════════════════════════════════════════════════
// Product catalog data — NO Prisma dependencies
// Importable by seed.ts, validation scripts, etc.
//
// 141 products: 67 Amazon (verified) + 74 SHEIN (extracted 2026-03-08)
// Amazon images confirmed working as of 2026-03-08.
// ═══════════════════════════════════════════════════════════════

export interface CatalogProduct {
  externalId: string;
  platform: 'AMAZON' | 'SHEIN';
  name: string;
  brand: string;
  price: number;
  currency: string;
  imageUrls: string[];
  productPageUrl: string;
  affiliateUrl: null;
  category: string;
  fashnCategory: string;
  availableSizes: string[];
  styleTags: string[];
  gender: 'FEMALE' | 'MALE' | 'UNISEX';
}

export interface CatalogPairing {
  top: string;
  bottom: string;
  gender: string;
  styleTags: string[];
}

// ═══════════════════════════════════════════════════════════════
// 141 Real Products — 67 Amazon + 74 SHEIN
// Distribution: 72 Women + 65 Men + 4 Unisex
// ═══════════════════════════════════════════════════════════════

export const products: CatalogProduct[] = [
  // ─── Women's Tops (15) ──────────────────────────────
  { externalId: 'B0FX338KX4', platform: 'AMAZON', name: 'Button Up Cut Out Sleeveless Colorblock Top', brand: 'Verdusa', price: 22.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61FVTloojEL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FX338KX4', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0CQXTJBY8', platform: 'AMAZON', name: 'Cap Sleeve Business Casual Tank Top', brand: 'WIHOLL', price: 18.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/718smjBH5VL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CQXTJBY8', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0C746SD2Y', platform: 'AMAZON', name: 'Cable Short Sleeve V Neck Knit Pullover', brand: 'Imily Bela', price: 25.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71dkXJHlFqL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0C746SD2Y', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0DHS3R55X', platform: 'AMAZON', name: 'Ruched Cap Sleeve Crew Neck T-Shirt', brand: 'SAMPEEL', price: 16.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71jDiEgmFfL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DHS3R55X', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','streetwear'], gender: 'FEMALE' },
  { externalId: 'B0FT2CC48Y', platform: 'AMAZON', name: 'Ruffle Colorblock Button Up Blouse', brand: 'Verdusa', price: 24.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71+3LEwG8eL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FT2CC48Y', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','casual'], gender: 'FEMALE' },
  { externalId: 'B0FN4HS99W', platform: 'AMAZON', name: 'Cap Sleeve Button Down U Neck Blouse', brand: 'WIHOLL', price: 19.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71-uD9yTXuL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FN4HS99W', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','formal'], gender: 'FEMALE' },
  { externalId: 'B0FR7CDKMT', platform: 'AMAZON', name: 'Rolled Short Sleeve Waffle Knit Top', brand: 'Sampeel', price: 17.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81ljc4abCTL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FR7CDKMT', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0CSSHP46K', platform: 'AMAZON', name: 'Short Sleeve Crewneck Slim Fit Knit Top', brand: 'PRETTYGARDEN', price: 21.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71ydPyWZFGL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CSSHP46K', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0FG7DNDBN', platform: 'AMAZON', name: 'Pearl Beaded Short Sleeve Tee Top', brand: 'Verdusa', price: 26.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/519AycXbPsL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FG7DNDBN', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0D2HTXRZF', platform: 'AMAZON', name: 'Short Sleeve V Neck Beach Vacation Tee', brand: 'Generic', price: 14.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71eJlWOWLUL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D2HTXRZF', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: 'B0DP2X2QCW', platform: 'AMAZON', name: 'Half Sleeve Ribbed V Neck Slim Fit Tee (3-Pack)', brand: 'Riyiper', price: 28.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81l3JNKl4XL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DP2X2QCW', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0D7PQRN7K', platform: 'AMAZON', name: 'Color Block Knit Hoodie Pullover Sweater', brand: 'MixShe', price: 32.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/715uRS+MeiL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D7PQRN7K', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['streetwear','casual'], gender: 'FEMALE' },
  { externalId: 'B0DKHMMQBJ', platform: 'AMAZON', name: 'Puff Short Sleeve Sweater Blouse', brand: 'WIHOLL', price: 23.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/814nzHYJWHL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DKHMMQBJ', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['formal','casual'], gender: 'FEMALE' },
  { externalId: 'B0F7QX62MV', platform: 'AMAZON', name: 'Striped Patchwork Collared Half Sleeve Top', brand: 'Floerns', price: 22.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61FITsiH+RL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0F7QX62MV', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0FNQGF8C3', platform: 'AMAZON', name: 'Cap Sleeve Crew Neck Business Casual Tee', brand: 'Verdusa', price: 19.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71W0kLDatkL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FNQGF8C3', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['L','XL','XXL','3XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },

  // ─── Women's Bottoms (12) ───────────────────────────
  { externalId: 'B0BQZYX9WN', platform: 'AMAZON', name: 'Wide Leg High Waisted Dressy Trousers', brand: 'GRAPENT', price: 35.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61gjlepkuBL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0BQZYX9WN', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0D986LTTT', platform: 'AMAZON', name: 'High Waisted Wide Leg Work Slacks', brand: 'NIMIN', price: 32.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/51qA5VQ8zEL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D986LTTT', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0G1RDB54C', platform: 'AMAZON', name: 'Wide Leg Stretchy Elastic Waist Dress Pants', brand: 'GRAPENT', price: 33.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61EtPr5PB9L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0G1RDB54C', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['formal','casual'], gender: 'FEMALE' },
  { externalId: 'B0BQZZR97L', platform: 'AMAZON', name: 'Wide Leg Flowy Office Trousers', brand: 'GRAPENT', price: 34.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61bXghYElYL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0BQZZR97L', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B07R54H2X4', platform: 'AMAZON', name: 'Wrinkle Free Relaxed Fit Straight Leg Pant', brand: 'Lee', price: 29.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71gKcqlFfnL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B07R54H2X4', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['2','4','6','8','10','12','14','16','18'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0B4VS9JJ1', platform: 'AMAZON', name: 'High Elastic Waist Wide Leg Suit Pants', brand: 'FUNYYZO', price: 31.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61Gk1S3bLTL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0B4VS9JJ1', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B085Q6KKV6', platform: 'AMAZON', name: 'Lightweight Athletic Tapered Joggers', brand: 'THE GYM PEOPLE', price: 27.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/510FRHf4JbL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B085Q6KKV6', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['sporty','casual'], gender: 'FEMALE' },
  { externalId: 'B0FPQRN4PB', platform: 'AMAZON', name: 'Pleated Wide Leg Baggy Dress Slacks', brand: 'Susclude', price: 33.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/51gH6obj1bL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FPQRN4PB', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','casual'], gender: 'FEMALE' },
  { externalId: 'B0FPR64PMK', platform: 'AMAZON', name: 'Lace Trim Wide Leg Dress Pants', brand: 'Susclude', price: 34.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/514smteTRVL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FPR64PMK', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0BMZF8QJD', platform: 'AMAZON', name: 'High Elastic Waist Straight Leg Trousers', brand: 'FUNYYZO', price: 30.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61iH4ZDpNTL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0BMZF8QJD', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0FW3XV9CQ', platform: 'AMAZON', name: 'Side Striped Wide Leg Business Pants', brand: 'GORGLITTER', price: 29.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/51OK7FpK8aL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FW3XV9CQ', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL'], styleTags: ['formal','streetwear'], gender: 'FEMALE' },
  { externalId: 'B0C2V7S82C', platform: 'AMAZON', name: 'High Waisted Flowy Wide Leg Trousers', brand: 'GRAPENT', price: 36.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61Uxzh9CujL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0C2V7S82C', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },

  // ─── Women's Dresses (11) ──────────────────────────
  { externalId: 'B082ZT6WBY', platform: 'AMAZON', name: 'Sleeveless Woven A-Line V Neck Shift Dress', brand: 'Amazon Essentials', price: 24.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61gkT3wjwNL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B082ZT6WBY', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['XS','S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0F1FTWD76', platform: 'AMAZON', name: 'Casual Short Sleeve T-Shirt Dress with Pockets', brand: 'ETCYY', price: 29.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81w1b4GWOAL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0F1FTWD76', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: 'B0FT4V4H3Q', platform: 'AMAZON', name: 'Flowy Casual Midi Dress with Pockets', brand: 'WIHOLL', price: 32.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/7191TnDL93L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FT4V4H3Q', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: 'B0DKDZB6WH', platform: 'AMAZON', name: 'Sleeveless Button Down Maxi Sundress', brand: 'MOLERANI', price: 33.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81Y2-SQYWzL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DKDZB6WH', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: 'B0CXPDRS29', platform: 'AMAZON', name: 'Sleeveless Spaghetti Strap Ruffle Maxi Dress', brand: 'PRETTYGARDEN', price: 39.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71qwUjryGiL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CXPDRS29', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['bohemian','casual'], gender: 'FEMALE' },
  { externalId: 'B0BXL73TBD', platform: 'AMAZON', name: 'V Neck Bohemian Geometric Maxi Dress', brand: 'miduo', price: 35.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71fNkkVNGbL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0BXL73TBD', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['bohemian','casual'], gender: 'FEMALE' },
  { externalId: 'B0DJ2RJ4JS', platform: 'AMAZON', name: 'V Neck Eyelet A-Line Flowy Midi Dress', brand: 'PRETTYGARDEN', price: 37.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71gi8EyrpnL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DJ2RJ4JS', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','formal'], gender: 'FEMALE' },
  { externalId: 'B0DK6YG2K6', platform: 'AMAZON', name: 'V Neck Bell Sleeve Tiered Floral Maxi Dress', brand: 'PRETTYGARDEN', price: 41.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/718u-jSEcIL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DK6YG2K6', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['bohemian','casual'], gender: 'FEMALE' },
  { externalId: 'B0CZCM6BHW', platform: 'AMAZON', name: 'Flowy Ruffle 3/4 Sleeve Tiered Mini Dress', brand: 'Generic', price: 28.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71RbLRc6NAL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CZCM6BHW', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['bohemian','casual'], gender: 'FEMALE' },
  { externalId: 'B0DQSK6KWY', platform: 'AMAZON', name: 'Halter V Neck A-Line Maxi Dress', brand: 'Narecte', price: 34.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71b-lFZMlqL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DQSK6KWY', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: 'B0FS6C43MM', platform: 'AMAZON', name: 'Button Front Sleeveless Casual Midi Sundress', brand: 'WIHOLL', price: 31.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81wIqRJLFaL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FS6C43MM', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },

  // ─── Men's Tops (15) ────────────────────────────────
  { externalId: 'B0FWC94795', platform: 'AMAZON', name: 'Knit Short Sleeve Classic Golf Polo', brand: 'Runcati', price: 24.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71nMFayTLtL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FWC94795', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'B0DJ8TLM7P', platform: 'AMAZON', name: 'Knit Button Down Crochet Golf Polo', brand: 'COOFANDY', price: 27.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81iiFh6StjL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DJ8TLM7P', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0G5MGQMTP', platform: 'AMAZON', name: 'Classic Short Sleeve Cotton Pique Polo', brand: 'COOFANDY', price: 22.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71C73b34wCL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0G5MGQMTP', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'B0G19HGXS4', platform: 'AMAZON', name: 'V Neck Ribbed Textured Stretch Polo', brand: 'COOFANDY', price: 25.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81px2HADjSL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0G19HGXS4', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0DJQTKRZC', platform: 'AMAZON', name: 'Button Beach Knit Stretchy Vacation Polo', brand: 'JMIERR', price: 23.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71tp4B1QenL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DJQTKRZC', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'MALE' },
  { externalId: 'B0DJQTQVX5', platform: 'AMAZON', name: 'Vacation Button Beach Knit Polo (Navy)', brand: 'JMIERR', price: 23.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81-SBYXI8TL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DJQTQVX5', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'MALE' },
  { externalId: 'B0FY2P2YDT', platform: 'AMAZON', name: 'Textured Knit Button Vacation Golf Polo', brand: 'JMIERR', price: 24.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/710mnvkP1uL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FY2P2YDT', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'B0DJQTN913', platform: 'AMAZON', name: 'Vacation Knit Stretchy Beach Polo (Green)', brand: 'JMIERR', price: 23.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71kClmrPCHL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DJQTN913', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'MALE' },
  { externalId: 'B0FY2NZLMN', platform: 'AMAZON', name: 'Textured Knit Button Casual Polo (White)', brand: 'JMIERR', price: 24.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71KCBZj+JtL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FY2NZLMN', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0DJQRWH7J', platform: 'AMAZON', name: 'Vacation Button Beach Polo (Beige)', brand: 'JMIERR', price: 23.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/812cHV4l9UL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DJQRWH7J', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0DJS7DRX9', platform: 'AMAZON', name: 'Short Sleeve Vintage Knit Golf Polo', brand: 'COOFANDY', price: 26.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81YUTXQPeML._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DJS7DRX9', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0936M17S7', platform: 'AMAZON', name: 'Moisture Wicking Quick-Dry Golf Polo', brand: 'Alex Vando', price: 19.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/91IFiEz8RbS._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0936M17S7', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['sporty','casual'], gender: 'MALE' },
  { externalId: 'B0CL79J2MK', platform: 'AMAZON', name: 'Knit Short Sleeve Button Down Beach Shirt', brand: 'COOFANDY', price: 28.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/81wHPAtN8mL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0CL79J2MK', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'MALE' },
  { externalId: 'B0DJQT3PSF', platform: 'AMAZON', name: 'Vacation Knit Stretchy Golf Polo (Brown)', brand: 'JMIERR', price: 23.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71Zl491KA8L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DJQT3PSF', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0FY2QGK2R', platform: 'AMAZON', name: 'Textured Knit Button Beach Polo (Black)', brand: 'JMIERR', price: 24.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/712EQ3pDmML._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FY2QGK2R', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },

  // ─── Men's Bottoms (10) ─────────────────────────────
  { externalId: 'B0FFGRZZ75', platform: 'AMAZON', name: 'Pleated Baggy Wide Leg Dress Pants', brand: 'Susclude', price: 32.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/51OLOJWjouL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FFGRZZ75', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','minimalist'], gender: 'MALE' },
  { externalId: 'B0G42J6ZC8', platform: 'AMAZON', name: 'Baggy Wide Leg Loose Fit Trousers', brand: 'Susclude', price: 30.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61so9FQ6MZL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0G42J6ZC8', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: 'B0G34PPWHZ', platform: 'AMAZON', name: 'Lightweight Pleated Wide Leg Dress Pants', brand: 'JMIERR', price: 31.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61gSY8uLs2L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0G34PPWHZ', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','casual'], gender: 'MALE' },
  { externalId: 'B0D8TFF3WY', platform: 'AMAZON', name: 'Elastic Waist Tapered Chino Golf Trousers', brand: 'JMIERR', price: 28.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61jk+hZ6VXL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0D8TFF3WY', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: 'B0FM8PZQG5', platform: 'AMAZON', name: 'Pleated Wide Leg Elastic Waist Trousers', brand: 'Generic', price: 29.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61FxIJslV7L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FM8PZQG5', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','minimalist'], gender: 'MALE' },
  { externalId: 'B0G4TWGTTF', platform: 'AMAZON', name: 'Pinstripe Wide Leg Baggy Dress Pants', brand: 'Susclude', price: 33.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71Jv1MlR6IL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0G4TWGTTF', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','minimalist'], gender: 'MALE' },
  { externalId: 'B0F9FF7M4Z', platform: 'AMAZON', name: 'Casual Loose Fit Pants with Belt Loops', brand: 'Heyfanee', price: 27.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/51xroPWkHzL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0F9FF7M4Z', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: 'B0FVXMH5RC', platform: 'AMAZON', name: 'Linen Elastic Waist Lightweight Straight Pants', brand: 'Runcati', price: 26.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/610080KuffL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FVXMH5RC', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'MALE' },
  { externalId: 'B01JQTOZKG', platform: 'AMAZON', name: 'Classic-Fit Wrinkle-Resistant Flat-Front Chino', brand: 'Amazon Essentials', price: 25.90, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/71De-IPZoeL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B01JQTOZKG', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['28','29','30','31','32','33','34','36','38','40','42'], styleTags: ['casual','formal'], gender: 'MALE' },
  { externalId: 'B0DPHRDFLN', platform: 'AMAZON', name: 'Elastic Waist Linen Straight Leg Trousers', brand: 'Runcati', price: 25.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/51PB8kOB3uL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DPHRDFLN', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'MALE' },

  // ─── Unisex Tops (4) ──────────────────────────────
  { externalId: 'B0DYJZRHX6', platform: 'AMAZON', name: 'Pleated Relaxed Fit Wide Leg Slacks', brand: 'Susclude', price: 31.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/51fm1F+QZ6L._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0DYJZRHX6', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','casual'], gender: 'UNISEX' },
  { externalId: 'B0FFB7TK28', platform: 'AMAZON', name: 'Pleated Baggy Wide Leg Vintage Slacks', brand: 'Susclude', price: 33.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/51WPkkiQ2kL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FFB7TK28', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'UNISEX' },
  { externalId: 'B0FM8KDGR8', platform: 'AMAZON', name: 'Pleated Wide Leg Loose Fit Trousers', brand: 'Generic', price: 29.49, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61aosjZU3KL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0FM8KDGR8', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'UNISEX' },
  { externalId: 'B0G34M1KFX', platform: 'AMAZON', name: 'Baggy Lightweight Pleated Relaxed Trousers', brand: 'JMIERR', price: 31.99, currency: 'USD', imageUrls: ['https://m.media-amazon.com/images/I/61XbtF8R7WL._AC_SX679_.jpg'], productPageUrl: 'https://www.amazon.com/dp/B0G34M1KFX', affiliateUrl: null, category: 'Unisex', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'UNISEX' },

  // ═══════════════════════════════════════════════════════════════
  // SHEIN Products (74) — Extracted 2026-03-08
  // ═══════════════════════════════════════════════════════════════

  // ─── SHEIN Women's Tops (14) ──────────────────────────
  { externalId: '48902379', platform: 'SHEIN', name: 'Multi Color Knitted Round Neck Long Sleeve Bodycon T-Shirt', brand: 'Comfortcana', price: 22.55, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/11/28/17/1732777486d9fa0485ab7ffad6a67919daa8736938_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Comfortcana-Multi-Color-Knitted-Women-s-Round-Neck-Long-Sleeve-Ruched-Bodycon-T-Shirt-p-48902379.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '42897956', platform: 'SHEIN', name: 'Casual Solid Color Short Sleeve T-Shirt', brand: 'Lymera', price: 10.42, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/09/18/4a/17266381957dd9b1f42887efc5abec2b66be6133d7_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Lymera-Women-s-Casual-Solid-Color-Black-White-Short-Sleeve-T-Shirt-Tops-For-Women-Fall-Autumn-And-Winter-Halloween-Work-Office-Occasion-For-Women-Going-Out-Party-Christmas-Thanksgiving-New-Year-Occasion-p-42897956.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '147036553', platform: 'SHEIN', name: 'Round Neck Short Sleeve Pleated Casual T-Shirt', brand: 'SHEIN', price: 16.91, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/08/07/d7/1754549695da20912cea2e5d66bd9caca9d4c0333c_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Women-s-Round-Neck-Short-Sleeve-Pleated-Casual-Versatile-T-Shirt-p-147036553.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '223977591', platform: 'SHEIN', name: 'Fitted Long Sleeve Square Neck Knit Top', brand: 'Vaiaye', price: 7.70, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/11/24/bc/176398020276c4d0c0a0ffc17ae8ec92cd959ecb39_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Vaiaye-Women-s-Spring-Summer-Sexy-Fitted-Long-Sleeve-Knit-Top-Solid-Color-Square-Neck-T-Shirt-Casual-Versatile-Minimalist-Casual-Daily-Wear-p-223977591.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '67665706', platform: 'SHEIN', name: 'Round Neck Fitted Ribbed Texture T-Shirt', brand: 'Easowa', price: 5.52, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/11/15/05/17631755078e11125ef7d417fd96d8f35b711f2f16_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Easowa-Women-s-Round-Neck-Fitted-Ribbed-Texture-T-Shirt-Casual-Vacation-Elegant-Everyday-Comfortable-Tee-p-67665706.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '31470482', platform: 'SHEIN', name: 'Waffle Pattern Round Neck Batwing Sleeve T-Shirt', brand: 'EMERY ROSE', price: 11.59, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/08/a5/17098684149e5ae3902e77b98a6d81adac130a7d8e_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/EMERY-ROSE-Women-s-Waffle-Pattern-Round-Neck-Batwing-Sleeve-T-Shirt-p-31470482.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: '97716834', platform: 'SHEIN', name: 'See Good In All Things Graphic Casual T-Shirt', brand: 'SHEIN', price: 12.38, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_spmp/2025/03/14/12/1741916871072fdb93f4b6516507cb76a7548276d6_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Women-See-Good-In-All-Things-Graphic-Print-Casual-T-Shirt-Beach-p-97716834.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['streetwear','casual'], gender: 'FEMALE' },
  { externalId: '306124467', platform: 'SHEIN', name: 'Casual Loose Batwing Striped T-Shirt', brand: 'Everyssa', price: 9.01, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/12/15/13/17657713168ba4b43c2054fdb06f5134414018b1d5_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Everyssa-Women-s-Casual-Loose-Batwing-Striped-T-Shirt-Autumn-p-306124467.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '64603795', platform: 'SHEIN', name: '3pcs Versatile Casual Short Sleeve T-Shirt Set', brand: 'INAWLY', price: 14.09, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2025/04/02/17/1743583839ebd19545e7e35bd999027390a1782a3d_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/INAWLY-3pcs-Set-Women-Versatile-Casual-Minimalist-Summer-Short-Sleeve-T-Shirt-Set-p-64603795.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '22131374', platform: 'SHEIN', name: 'Oblique Shoulder Long Sleeve Fitted T-Shirt', brand: 'SHEIN', price: 8.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2023/08/28/6d/1693188831b7367cff8deccdd1bec572dad2381b67_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-Frenchy-Solid-Color-Oblique-Shoulder-Long-Sleeve-Fitted-Fashionable-Versatile-Minimalist-Design-T-Shirt-Winter-Black-Casual-Spring-p-22131374.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '47687467', platform: 'SHEIN', name: '4pcs Solid Color Short Sleeve Crew Neck T-Shirts', brand: 'Chiquease', price: 12.57, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/11/15/0a/1731635068272f867672720b73f7ac15a374f4b53e_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Chiquease-4pcs-Women-Solid-Color-Short-Sleeve-Crew-Neck-Tight-Fit-Basic-T-Shirts-p-47687467.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '32568784', platform: 'SHEIN', name: 'Holiday Lace Spliced Batwing Sleeve Blouse', brand: 'SHEIN', price: 9.95, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/04/02/62/1712026906b37a4a894fc5fabb4edbd2c597317107_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-Frenchy-Holiday-Leisure-Lace-Spliced-Women-Shirts-Summer-Blouse-Teacher-Shirts-Short-Sleeve-Shirts-Summer-T-Shirts-Work-Shirts-Summer-Sweater-Textured-Batwing-Sleeve-T-Shirt-Summer-Fits-Casual-Shirts-Plain-T-Shirt-Summer-Outfits-Green-Christmas-p-32568784.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: '115531692', platform: 'SHEIN', name: 'Hip Hop Graphic Print Round Neck T-Shirt', brand: 'SHEIN', price: 4.98, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/07/12/91/1752298957bb82f2f8c740785e6ac4bb8ea796c215_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Women-Men-Mariah-Scientist-Rapper-Young-Hip-Hop-Tee-Tshirt-Women-Tee-Classic-Free-Thugs-Print-Round-Neck-Short-Sleeve-T-Shirt-Y2K-Vintage-Streetwear-Graphic-Oversized-Cotton-Women-Tops100-Cotton-Crew-Neck-Comfortable-T-Shirt-Gender-Neutral-100-Cotton-Retro-Futuristic-Tee-Bold-Statement-PrintUnique-Print-Vintage-Black-White-Print-Oversized-Tee-Unisex-Hippie-Essential-p-115531692.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['streetwear','casual'], gender: 'FEMALE' },
  { externalId: '178715214', platform: 'SHEIN', name: '4pcs Basic Round Neck Short Sleeve Fitted T-Shirts', brand: 'SHEIN', price: 13.90, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/10/4e/175749731846bab3e6b17c043db8ae9a9758a89f09_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-EZwear-4pcs-Set-Black-Pink-Gray-White-Casual-Round-Neck-Short-Sleeve-Fitted-Women-T-Shirts-Suitable-For-Summer-p-178715214.html', affiliateUrl: null, category: 'Women Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },

  // ─── SHEIN Women's Bottoms (10) ───────────────────────
  { externalId: '73404367', platform: 'SHEIN', name: 'Loose Fit Solid Color Knitted Jogger Pants', brand: 'SHEIN', price: 4.75, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/05/06/4b/1746499450fcd3f037ec36ef96f155f17155a24c26_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-BASICS-Women-s-Loose-Fit-Solid-Color-Knitted-Casual-Jogger-Pants-With-Pockets-p-73404367.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['sporty','casual'], gender: 'FEMALE' },
  { externalId: '183214571', platform: 'SHEIN', name: '100% Cotton Low Waist Straight Pants', brand: 'SHEIN', price: 18.88, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/15/d2/17579256196496db1a14080773493efa23390f6ff1_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-PETITE-100-Washed-Cotton-Low-Waist-Straight-Pants-Linen-Pants-For-Women-Women-Pants-For-Summer-Cotton-Pants-Women-Wide-Leg-Pants-Women-Pants-For-Summer-Fall-Fall-Clothes-For-Women-Women-S-Pants-For-Summer-p-183214571.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '42640740', platform: 'SHEIN', name: 'Solid High Rise Flap Pocket Overalls', brand: 'SHEIN', price: 6.66, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_spmp/2024/08/28/f2/172478188810df182f93e06e8f062c2a5a09af2e21_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Solid-High-Rise-Flap-Pocket-Overalls-p-42640740.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','streetwear'], gender: 'FEMALE' },
  { externalId: '411920692', platform: 'SHEIN', name: 'Solid Color Zipper Pocket Suit Pants', brand: 'SHEIN', price: 15.28, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2026/01/10/25/1768048711825c358a69ac19b8a876322bed5d4f4a_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Solid-Color-Zipper-Pocket-Button-Waistless-Elegant-Fashion-Versatile-Suit-Pants-For-Commuting-p-411920692.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: '91988558', platform: 'SHEIN', name: 'Solid Color Wide Leg Casual Pants', brand: 'Franclia', price: 12.95, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/10/03/85/1759482025f8acb9d918acda5e18b20b4498e7762a_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Franclia-Women-s-Solid-Color-Toothpick-Stripe-Design-Wide-Leg-Casual-Pants-For-Commuter-Casual-Outfits-Spring-Clothes-For-University-Fall-Cloth-For-Women-p-91988558.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '49233274', platform: 'SHEIN', name: 'High Waisted Elastic Flare Yoga Pants', brand: 'Slaydiva', price: 11.00, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/12/02/95/173310849693c10c157e90a951077c7011eafbd8e0_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Slaydiva-Women-s-High-Waisted-Elastic-Slimming-Flare-Yoga-Pants-Flared-Sweatpants-For-Women-p-49233274.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['sporty','casual'], gender: 'FEMALE' },
  { externalId: '10643526', platform: 'SHEIN', name: 'High Waist Press Crease Tapered Pants', brand: 'SHEIN', price: 12.06, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/09/d2/1757400002b94cb1c7b297840df6bc49a3c46aa3b0_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-PETITE-High-Waist-Press-Crease-Tapered-Black-Summer-Pants-p-10643526.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['formal','minimalist'], gender: 'FEMALE' },
  { externalId: '200537309', platform: 'SHEIN', name: 'Casual Solid Color Suit Pants', brand: 'Airaco', price: 13.75, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/10/25/fa/176135980535466850d4acee4a712d990e8645f236_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Airaco-Women-s-Casual-Solid-Color-Suit-Pants-p-200537309.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['formal','casual'], gender: 'FEMALE' },
  { externalId: '212592577', platform: 'SHEIN', name: '3pcs High Waist Drawstring Straight Pants Set', brand: 'SHEIN', price: 32.79, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/10/12/db/1760254457fb91670348b4c07ba4c62701ee210afc_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-Essnce-3pcs-Women-Casual-Solid-Color-Versatile-High-Waist-Drawstring-Pocket-Straight-Loose-Pants-Set-Suitable-For-Spring-Summer-p-212592577.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '32258906', platform: 'SHEIN', name: 'Solid Color Pleated Casual Straight Pants', brand: 'SHEIN', price: 13.42, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/10/27/6d/1761535757b2a7d77d85210a4449fb9039c6498798_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-PETITE-Women-s-Solid-Color-Pleated-Casual-Straight-Pants-Fall-Cloth-For-Women-p-32258906.html', affiliateUrl: null, category: 'Women Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL'], styleTags: ['formal','casual'], gender: 'FEMALE' },

  // ─── SHEIN Women's Dresses (10) ──────────────────────
  { externalId: '66590724', platform: 'SHEIN', name: 'Vacation Casual Striped Dress', brand: 'Breezaya', price: 12.16, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/04/14/6e/174462450219fc12cee2ce06a1a13725269f4985e6_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Breezaya-Vacation-Casual-Striped-Women-s-Dress-Fashionable-For-Summer-p-66590724.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: '66071013', platform: 'SHEIN', name: 'Leopard Print Ruched Waist Stand Collar Dress', brand: 'Trelyra', price: 12.87, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/17/57/175808952955a0fbbf1f904845b1c261654095ee3e_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Trelyra-Leopard-Print-Ruched-Waist-Stand-Collar-Vacation-Dress-p-66071013.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: '40300919', platform: 'SHEIN', name: 'Floral Print Shirt Dress', brand: 'SHEIN', price: 13.42, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/08/07/d3/1723042822f5c1a82aa6f76a355e5a8cca8e4c2995_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-Clasi-Summer-Vacation-Outfits-Women-s-Autumn-Winter-Fashionable-Versatile-Commuter-Floral-Print-Shirt-Dress-Fall-Women-Clothes-Dress-Summer-Dresses-For-Women-p-40300919.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: '68937832', platform: 'SHEIN', name: 'Leaf Print Round Neck Sleeveless Drawstring Dress', brand: 'SHEIN', price: 7.73, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/04/22/f4/1745286929438066a44e263385baf681175c495d26_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SHEIN-LUNE-Summer-Casual-Leaf-Printed-Round-Neck-Sleeveless-Drawstring-Waist-Dress-Vacation-Beach-Outfits-Women-p-68937832.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: '83542036', platform: 'SHEIN', name: 'Bohemian Striped Fish Scale Print Sleeveless Dress', brand: 'SHEIN', price: 13.09, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/12/25/06/17666279879495ff5356ce603f53a2e2ed9ba52e22_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Starfish-Bohemian-Style-Summer-Beach-Casual-Comfortable-Vintage-Colorblock-Striped-Fish-Scale-Print-Sleeveless-Dress-Brunch-Outfit-For-Women-p-83542036.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['bohemian','casual'], gender: 'FEMALE' },
  { externalId: '36216653', platform: 'SHEIN', name: 'Solid Color Simple Daily Sleeveless Dress', brand: 'Breezaya', price: 11.87, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/06/04/22/1717482533d313a20220f719b880f0f8c655dff864_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Breezaya-Women-s-Solid-Color-Simple-Daily-Sleeveless-Dress-Vacation-Beach-Outfit-p-36216653.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '27609504', platform: 'SHEIN', name: 'Patchwork Lace Back Hollow Knotted Dress', brand: 'Breezaya', price: 15.16, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2023/12/13/c4/1702439788ba1c9bce30102f9b2b5c13bbbc01f0ea_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Breezaya-Women-s-Patchwork-Lace-Back-Hollow-Knotted-Dress-Vacation-Beach-Outfit-p-27609504.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: '31396436', platform: 'SHEIN', name: 'Short Puff Sleeve V Neck Plant Print Dress', brand: 'EMERY ROSE', price: 14.67, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/13/a8/1710293250197d369847eb899cba133cc6f9fc3916_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/EMERY-ROSE-Women-s-Short-Puff-Sleeve-Vacation-Dress-With-Plant-Print-V-Neck-Design-p-31396436.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },
  { externalId: '60370059', platform: 'SHEIN', name: 'Casual Solid Color Sleeveless Mid-Length Dress', brand: 'INAWLY', price: 10.36, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/06/06/5e/174919968340abd0b575f40cfe69402f1503b4de91_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/INAWLY-Women-s-Casual-Solid-Color-Sleeveless-Mid-Length-Dress-For-Daily-Wear-p-60370059.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','minimalist'], gender: 'FEMALE' },
  { externalId: '31667410', platform: 'SHEIN', name: 'Allover Printed Sleeveless Round Neck Dress', brand: 'Breezaya', price: 8.66, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/18/9b/1710743569b2b76035481b4f018fc88a6214fdfc59_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Breezaya-Allover-Printed-Sleeveless-Round-Neck-Straight-Fit-Dress-Vacation-Beach-Outfits-Women-p-31667410.html', affiliateUrl: null, category: 'Women Dresses', fashnCategory: 'one-pieces', availableSizes: ['S','M','L','XL'], styleTags: ['casual','bohemian'], gender: 'FEMALE' },

  // ─── SHEIN Men's Tees (10) ────────────────────────────
  { externalId: '84491724', platform: 'SHEIN', name: 'Fashion Printed Loose Fit Short Sleeve T-Shirt', brand: 'SHEIN', price: 6.71, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/05/20/5f/17477312933c9ec6f1b1ac1670d96f9921a3c09c8a_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Men-Fashion-Printed-Loose-Fit-Short-Sleeve-T-Shirt-Elegant-Design-Essential-For-Summer-Easy-To-Match-Showcase-Your-Style-p-84491724.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '186441346', platform: 'SHEIN', name: 'Vintage Boxing Graphic T-Shirt', brand: 'SHEIN', price: 13.38, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/08/28/92/175638928354a5a8b8e329b5ed3f0a970b6c8716f9_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Vintage-Mike-Tyson-Shirt-Mike-Tyson-Tshirt-Mike-Tyson-T-Shirt-Boxing-Graphic-p-186441346.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '158173353', platform: 'SHEIN', name: 'Casual Solid Color Short Sleeve T-Shirt', brand: 'Manfinity', price: 7.22, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/08/20/e4/175566905235f5e2580967620a62951c91b221e442_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Homme-Men-s-Casual-Solid-Color-Short-Sleeve-T-Shirt-Summer-p-158173353.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: '395384622', platform: 'SHEIN', name: 'Striped Print Retro Short Sleeve T-Shirt', brand: 'Manfinity', price: 12.15, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2026/02/03/96/1770082477afd104c5f441e3aa1812f2def4b4a125_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Dauomo-Casual-Fashionable-Men-s-Striped-Print-Retro-Short-Sleeve-T-Shirt-Spring-Summer-p-395384622.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: '91494840', platform: 'SHEIN', name: '5pcs Regular Fit Short Sleeve T-Shirts', brand: 'SHEIN', price: 20.00, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/03/21/ef/1711005624d9d7189ce6fa35f623190b422dcc6b48_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/5pcs-Men-s-Regular-Fit-Short-Sleeve-T-Shirts-Solid-Color-Basic-Casual-Sports-Lightweight-Tops-Tee-p-91494840.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: '203239761', platform: 'SHEIN', name: 'Letter Print Round Neck Casual T-Shirt', brand: 'PAVTROS', price: 8.53, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/30/01/17592357039c19c9986c3fb4376f008ae7ba56b6ac_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/PAVTROS-Men-s-Letter-Print-Round-Neck-Casual-Loose-T-Shirt-p-203239761.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '99412062', platform: 'SHEIN', name: 'Fashionable Printed Loose Short Sleeve T-Shirt', brand: 'GRDR', price: 7.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/11/18/58/1763446908e672bb0fcef8b3561e029b426a713a1e_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/GRDR-Men-s-Fashionable-Printed-Loose-Short-Sleeve-T-Shirt-Exquisite-Design-Summer-Essential-Easy-To-Match-Showcase-Your-Style-p-99412062.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '68766666', platform: 'SHEIN', name: 'Knitted Casual Loose Fit Patchwork T-Shirt', brand: 'AXEPEAK', price: 7.75, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/04/21/d8/17451976664b7cd714f0506b910930a0d1bb5e8c1d_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/AXEPEAK-Men-s-Knitted-Casual-Everyday-Loose-Fit-Short-Sleeve-Patchwork-T-Shirt-Summer-Streetwear-Essentials-p-68766666.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','streetwear'], gender: 'MALE' },
  { externalId: '332561193', platform: 'SHEIN', name: 'Funny Gym Salt Sugar Trust Graphic T-Shirt', brand: 'SHEIN', price: 4.45, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/12/03/be/1764732348d0637b995c15a6e77fffc514a8adabcc_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Men-s-Funny-Gym-T-Shirt-With-Salt-Sugar-Trust-Graphic-Print-200g-Heavyweight-Cotton-Relaxed-Fit-Breathable-Short-Sleeve-Crew-Neck-Casual-Workout-Shirt-For-Summer-Salt-Shaker-Design-Fitness-Apparel-For-Salt-Lovers-Machine-Washable-Black-With-White-Salt-Crystal-Print-Loose-Fit-Outdoor-Fitness-Top-Geometric-Pattern-Adult-Men-s-Fashion-Humorous-Salt-Themed-Design-p-332561193.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '214311839', platform: 'SHEIN', name: 'Japanese Crane Print Short Sleeve T-Shirt', brand: 'Zrgoth', price: 7.89, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/11/22/c7/17637928733930507cc0addd2aa68470da920dbf49_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Zrgoth-Men-s-Casual-Versatile-Minimalist-Japanese-Crane-Print-Short-Sleeve-T-Shirt-p-214311839.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },

  // ─── SHEIN Men's Polos (10) ───────────────────────────
  { externalId: '162986982', platform: 'SHEIN', name: 'Contrast Color Short Sleeve Polo Shirt', brand: 'Manfinity', price: 13.38, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/08/26/34/17561722290d7744dd6db2d1408578cd25c41a2125_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-CasualCool-Men-s-Contrast-Color-Short-Sleeve-Casual-Commuter-Polo-Shirt-Men-Knitted-Polo-Shirt-Cream-Polo-Shirt-Men-Mens-V-Neck-Knitted-Shirt-Mens-Short-Sleeve-Sweater-Polo-Mens-Textured-Polo-Shirt-Old-Money-p-162986982.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','formal'], gender: 'MALE' },
  { externalId: '186848018', platform: 'SHEIN', name: 'Lightweight Linen Long Sleeve Half Zip Polo', brand: 'SHEIN', price: 12.50, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/09/15/54/1757915690957bebccb38ad0a8b66826b43a24463f_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Men-s-Lightweight-Linen-Long-Sleeve-Polo-Shirt-Half-Zip-Button-Design-Breathable-And-Comfortable-Suitable-For-Beach-Outdoor-Activities-Family-Gatherings-Note-White-Light-Blue-Etc-Colors-Are-Slightly-Sheer-European-And-American-Sizes-Run-Large-Recommend-Ordering-One-Size-Down-p-186848018.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','bohemian'], gender: 'MALE' },
  { externalId: '58500845', platform: 'SHEIN', name: 'Geometric Diamond Textured Knit Polo', brand: 'Manfinity', price: 15.59, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2025/02/17/77/1739774746c5e920376d3ae51cc7f3fd36e18ca351_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-CasualCool-Men-s-Vacation-Casual-Style-With-An-INS-Inspired-Look-A-Geometric-Diamond-Textured-Jacquard-Knit-Short-Sleeve-Khaki-Polo-Shirt-With-A-Button-Placket-Perfect-For-Music-Festivals-And-Hawaiian-Beach-Vacations-As-Well-As-Everyday-Wear-An-Ideal-Gift-For-A-Boyfriend-Or-Husband-Offers-A-French-Elegance-And-Romance-Men-s-Geometric-Stripe-Textured-Casual-Polo-Shirt-Polo-For-Men-Polo-Shirts-For-Men-Collar-Old-Money-Style-p-58500845.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','formal'], gender: 'MALE' },
  { externalId: '29696334', platform: 'SHEIN', name: 'Contrast Color Short Sleeve Polo with Details', brand: 'Manfinity', price: 10.02, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/01/29/7c/1706512761666151d5dc732d6111426c1a739e7249_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-CasualCool-Men-s-Contrast-Color-Short-Sleeve-Polo-Shirt-With-Decorative-Details-p-29696334.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','sporty'], gender: 'MALE' },
  { externalId: '351050460', platform: 'SHEIN', name: 'Casual Business Striped Design Polo Shirt', brand: 'Manfinity', price: 14.09, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2026/01/20/fa/17688744095d80b38cd4bb57e5475b38ffb0de62f7_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-CasualCool-Men-s-Casual-Business-Striped-Design-Polo-Shirt-Suitable-For-Daily-Commute-And-Casual-Versatile-Wear-Men-Buttoned-Knitted-Polo-Official-Polo-Elegant-Polo-p-351050460.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','casual'], gender: 'MALE' },
  { externalId: '157638467', platform: 'SHEIN', name: 'Textured Casual White Golf Polo Shirt', brand: 'Manfinity', price: 12.83, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/08/20/4d/1755652657329d6b4c26118e682a5cb4268c43782f_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-CasualCool-Men-s-Textured-Casual-Polo-Shirt-White-Golf-Shirt-Men-Mens-Short-Sleeve-Polo-Shirt-Mens-Textured-Polo-Shirt-Mens-Summer-Polo-Shirt-Mens-White-Polo-Shirt-p-157638467.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: '43295479', platform: 'SHEIN', name: 'Solid Color Button Long Sleeve Collar Polo', brand: 'Manfinity', price: 14.53, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/09/23/9c/1727079687df36b3418eed2a7b2472b0d58b3fc073_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Mode-1pc-Men-Solid-Color-Plain-Front-Button-Long-Sleeve-Simple-Collar-Polo-Shirt-Casual-Everyday-Wear-For-Work-For-Husband-For-Fall-p-43295479.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['formal','casual'], gender: 'MALE' },
  { externalId: '280842635', platform: 'SHEIN', name: 'Casual Solid Color Long Sleeve Polo Shirt', brand: 'Manfinity', price: 16.57, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/11/11/43/1762838179be6d4027791ec0853d43271a53f60289_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Homme-Men-s-Casual-Solid-Color-Long-Sleeve-Polo-Shirt-Versatile-For-Autumn-Winter-Mens-Knit-Shirt-Earthy-Clothes-Men-Brown-Sweater-Men-p-280842635.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: '181200554', platform: 'SHEIN', name: 'Oversized Asymmetrical Color Block Long Sleeve Polo', brand: 'Manfinity', price: 14.49, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/11/15/4b/1763173710cf94b03ca40851f862688328c80c4294_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Dauomo-Men-s-Oversized-Asymmetrical-Pattern-Color-Block-Long-Sleeve-Polo-Shirt-Fall-p-181200554.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '51905669', platform: 'SHEIN', name: 'Textured Design Polo Shirt', brand: 'Manfinity', price: 13.00, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2024/12/30/2e/17355298831e7021f6479ce528066685450673165a_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Homme-Manfinity-Men-s-Textured-Design-Polo-Shirt-p-51905669.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },

  // ─── SHEIN Men's Bottoms (10) ─────────────────────────
  { externalId: '147211871', platform: 'SHEIN', name: 'Letter Print Drawstring Waist Loose Sweatpants', brand: 'SHEIN', price: 10.76, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2025/02/19/7d/1739951514903aa4b24e199406fb954a1267dc7c9d_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Men-s-Letter-Print-Drawstring-Waist-Pocket-Loose-Fit-Casual-Sweatpants-p-147211871.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '89109007', platform: 'SHEIN', name: 'Striped Print Zipper Crossover Loose Pants', brand: 'SWAVVY', price: 26.69, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/05/30/ae/174857601525816a89d0df8701163e023fe9b0ea98_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/SWAVVY-Men-s-Striped-Print-Zipper-Crossover-Loose-Pants-Fall-p-89109007.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '43659610', platform: 'SHEIN', name: 'Loose Casual Pants Adjustable Waist', brand: 'Blueplus', price: 12.33, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_spmp/2024/09/19/62/17267325569851c19994039de7687ff7ebaeb6e6cc_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Blueplus-Men-s-Loose-Casual-Pants-1pc-Soft-And-Slightly-Elastic-Comfortable-And-Breathable-With-An-Adjustable-Waist-Suitable-For-Outdoor-Sports-And-Fitness-Activities-In-All-Seasons-p-43659610.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['sporty','casual'], gender: 'MALE' },
  { externalId: '150506260', platform: 'SHEIN', name: 'Casual Contrast Color Patchwork Sweatpants', brand: 'Manfinity', price: 15.89, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/08/12/bc/1754987993965357f8979c1e15df3a981088c0ea9a_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-EMRG-Men-s-Casual-Versatile-Contrast-Color-Patchwork-Sweatpants-p-150506260.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '329880153', platform: 'SHEIN', name: 'Solid Color Drawstring Sports Pants', brand: 'SHEIN', price: 7.65, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2026/01/26/9b/1769441484793c64f772f1ffe3fb2dc6176721b67d_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Men-s-Solid-Color-Drawstring-Sports-Pants-Suitable-For-Outdoor-Jogging-Gym-Workout-Single-Leg-Nine-Minute-Pants-Spring-And-Autumn-Men-s-Sports-Casual-Pants-p-329880153.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['sporty','casual'], gender: 'MALE' },
  { externalId: '64093471', platform: 'SHEIN', name: 'Casual Frayed Edge Drawstring Waist Shorts', brand: 'Manfinity', price: 8.73, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2025/04/01/94/1743491900b7de59e63bd79a8d6aac77fea72b7a12_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-EMRG-Men-s-Summer-Casual-Frayed-Edge-Drawstring-Waist-Shorts-Versatile-For-Everyday-Wear-p-64093471.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','streetwear'], gender: 'MALE' },
  { externalId: '207283978', platform: 'SHEIN', name: 'Solid Color Casual Loose Fit Baggy Pants', brand: 'Manfinity', price: 14.69, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/10/08/97/17599006645d588f4a9674306ca320570ebd6b4c82_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-EMRG-Men-s-Solid-Color-Casual-Loose-Fit-Pants-Men-Oversized-Pants-Black-Baggy-Sweat-Pants-Men-Japanese-Pants-For-Men-Korean-Pants-Men-Men-Loose-Fit-Pants-p-207283978.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','streetwear'], gender: 'MALE' },
  { externalId: '162746956', platform: 'SHEIN', name: 'Street Style Jogger Pants with Side Stripes', brand: 'SHEIN', price: 13.58, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/08/18/c2/1755501173e41eab42c9e34468624f3e4911665dce_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Men-s-Street-Style-Jogger-Pants-With-Side-Stripes-Pockets-And-Drawstring-Waist-Contrast-Color-Casual-Sweatpants-p-162746956.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','sporty'], gender: 'MALE' },
  { externalId: '41187955', platform: 'SHEIN', name: 'Street Collegiate Style Pants', brand: 'Manfinity', price: 11.43, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/16/fe/1758009112f80a885a860f774ab95b6ce6c3a559f5_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Hypemode-Men-s-Street-Collegiate-Style-Pants-Fall-p-41187955.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '104032049', platform: 'SHEIN', name: 'Casual Street Cross Print Loose Jogger Pants', brand: 'SHEIN', price: 16.89, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/p/spmp/2025/06/05/96/1749103551308c22c3da18da79dd92b00e6b0d38e8_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Men-s-Casual-Street-Cross-Print-Loose-Straight-Jogger-Pants-p-104032049.html', affiliateUrl: null, category: 'Men Bottoms', fashnCategory: 'bottoms', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },

  // ─── SHEIN Men's Hoodies & Sweatshirts (10) ──────────
  { externalId: '163942859', platform: 'SHEIN', name: 'Eye Minimalist Printed Zip Up Hooded Sweatshirt', brand: 'ROMWE', price: 19.94, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/12/39/175764874949579f5b95cda9d689f9116e19588c4c_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/ROMWE-MEN-Street-Life-Spring-Casual-Graphic-Men-S-Eye-Minimalist-Printed-Long-Sleeve-Zip-Up-Hooded-Sweatshirt-Fall-Winter-p-163942859.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '153186567', platform: 'SHEIN', name: 'Solid Color Minimalist Half Zip Sweatshirt', brand: 'SHEIN', price: 14.73, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/09/16/4d/1758019928c8a7d2e2c53f11a3e521e5027addf4fb_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/New-Men-s-Solid-Color-Minimalist-Half-Zip-Sweatshirt-Fashion-Autumn-Winter-Casual-Loose-Crew-Neck-Sweatshirt-p-153186567.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: '195598268', platform: 'SHEIN', name: 'Retro Virgin Mary Striped Pullover Sweatshirt', brand: 'ROMWE', price: 14.13, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/25/e7/1758796101ff71e6b6c1af6af29deea5221e82fc65_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/ROMWE-MEN-Street-Life-Spring-Casual-Graphic-Men-Retro-Virgin-Mary-Striped-Letter-Graphic-Print-Street-Style-Pullover-Sweatshirt-Fall-p-195598268.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '188784152', platform: 'SHEIN', name: 'Knitted Casual Loose Fit Long Sleeve Hoodie', brand: 'AXEPEAK', price: 23.59, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/19/bd/1758265669281f58a384d80607030d3411e9581478_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/AXEPEAK-Men-s-Knitted-Casual-Loose-Fit-Long-Sleeve-Hoodie-For-Fall-Winter-p-188784152.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','streetwear'], gender: 'MALE' },
  { externalId: '183086162', platform: 'SHEIN', name: 'Casual Short Hooded Zip Up Cardigan', brand: 'Manfinity', price: 22.98, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/15/d7/175791656705f4bf7093f6cc5aa0d1e1bb908729f9_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Hypemode-Men-s-Casual-Short-Hooded-Cardigan-Plain-Hoodie-Oversized-Zip-Up-Hoodie-Cropped-Zip-Up-Men-Boxy-Double-Zipper-Hoodie-p-183086162.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','streetwear'], gender: 'MALE' },
  { externalId: '163519923', platform: 'SHEIN', name: 'American Eye Graphic Print Short Hoodie', brand: 'ROMWE', price: 19.94, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/09/11/8c/1757560154c2c9ec653bdcdbc116dfbcd85d8e672a_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/ROMWE-MEN-Street-Life-Spring-Casual-Graphic-Men-S-Hooded-Sweatshirt-Casual-Street-Style-Popular-American-Eye-Graphic-Print-Short-Hoodie-Autumn-Winter-Long-Sleeve-Top-p-163519923.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '234758164', platform: 'SHEIN', name: 'Angel Print Zip Up Hooded Thermal Sweatshirt', brand: 'ROMWE', price: 19.23, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2026/02/02/12/17700205070e2f758054a6ef8e75867ad8c4e7530e_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/ROMWE-MEN-Street-Life-Spring-Casual-Graphic-Men-S-Fashion-Street-Angel-Print-Zip-Up-Drawstring-Hooded-Thermal-Lined-Sweatshirt-Autumn-Winter-p-234758164.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '59933078', platform: 'SHEIN', name: 'Knitted Casual Loose Fit Long Sleeve Sweatshirt', brand: 'Manfinity', price: 15.83, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/images3_pi/2025/03/06/16/1741271897a5ac106b4e1972abd6cf8afa1e6a163c_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Manfinity-Unisex-Men-s-Knitted-Casual-Loose-Fit-Long-Sleeve-Sweatshirt-Fashionable-And-Suitable-For-Young-People-Autumn-Winter-Couple-Things-p-59933078.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['casual','minimalist'], gender: 'MALE' },
  { externalId: '182070110', platform: 'SHEIN', name: 'Faith Over Fear Letter Print Pocket Hoodie', brand: 'SHEIN', price: 6.99, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/spmp/2025/09/15/21/1757920000eaf156c11c3e2d2c7f99d27e13bb16cc_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/Faith-Over-Fear-Letter-Print-Pocket-Hoodie-Men-s-Casual-Long-Sleeve-Drawstring-Style-Autumn-Winter-New-Unisex-Loose-Fit-Hooded-Sweatshirt-K88-p-182070110.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
  { externalId: '125676946', platform: 'SHEIN', name: 'Creative Portrait Graphic Hooded Sweatshirt', brand: 'ROMWE', price: 16.71, currency: 'USD', imageUrls: ['https://img.ltwebstatic.com/v4/j/pi/2025/12/26/42/176671677189bbdb680db18db5c2173b789eeb144d_thumbnail_600x.webp'], productPageUrl: 'https://us.shein.com/ROMWE-MEN-Street-Life-Spring-Casual-Graphic-Men-S-Hooded-Drawstring-Long-Sleeve-Casual-Creative-Portrait-Graphic-Sweatshirt-Fall-Winter-p-125676946.html', affiliateUrl: null, category: 'Men Tops', fashnCategory: 'tops', availableSizes: ['S','M','L','XL','XXL'], styleTags: ['streetwear','casual'], gender: 'MALE' },
];

// ═══════════════════════════════════════════════════════════════
// 42 Outfit Pairings — referenced by product externalId
// 24 Amazon + 18 SHEIN
// ═══════════════════════════════════════════════════════════════

export const outfitPairings: CatalogPairing[] = [
  // ─── Amazon Women's Outfits (12) ──────────────────────
  { top: 'B0FX338KX4', bottom: 'B0BQZYX9WN', gender: 'W', styleTags: ['formal','minimalist'] },
  { top: 'B0CQXTJBY8', bottom: 'B0D986LTTT', gender: 'W', styleTags: ['casual','formal'] },
  { top: 'B0C746SD2Y', bottom: 'B0G1RDB54C', gender: 'W', styleTags: ['casual','minimalist'] },
  { top: 'B0DHS3R55X', bottom: 'B085Q6KKV6', gender: 'W', styleTags: ['casual','sporty'] },
  { top: 'B0FT2CC48Y', bottom: 'B0B4VS9JJ1', gender: 'W', styleTags: ['formal','casual'] },
  { top: 'B0FN4HS99W', bottom: 'B0FPQRN4PB', gender: 'W', styleTags: ['casual','formal'] },
  { top: 'B0FR7CDKMT', bottom: 'B0BQZZR97L', gender: 'W', styleTags: ['casual','minimalist'] },
  { top: 'B0CSSHP46K', bottom: 'B0FPR64PMK', gender: 'W', styleTags: ['formal','minimalist'] },
  { top: 'B0D7PQRN7K', bottom: 'B07R54H2X4', gender: 'W', styleTags: ['streetwear','casual'] },
  { top: 'B0DKHMMQBJ', bottom: 'B0FW3XV9CQ', gender: 'W', styleTags: ['formal','streetwear'] },
  { top: 'B0F7QX62MV', bottom: 'B0BMZF8QJD', gender: 'W', styleTags: ['formal','minimalist'] },
  { top: 'B0FNQGF8C3', bottom: 'B0C2V7S82C', gender: 'W', styleTags: ['casual','bohemian'] },

  // ─── Amazon Men's Outfits (10) ────────────────────────
  { top: 'B0FWC94795', bottom: 'B0FFGRZZ75', gender: 'M', styleTags: ['casual','formal'] },
  { top: 'B0DJ8TLM7P', bottom: 'B0G34PPWHZ', gender: 'M', styleTags: ['casual','formal'] },
  { top: 'B0G5MGQMTP', bottom: 'B0D8TFF3WY', gender: 'M', styleTags: ['casual','sporty'] },
  { top: 'B0G19HGXS4', bottom: 'B01JQTOZKG', gender: 'M', styleTags: ['casual','formal'] },
  { top: 'B0DJQTKRZC', bottom: 'B0FVXMH5RC', gender: 'M', styleTags: ['casual','bohemian'] },
  { top: 'B0DJS7DRX9', bottom: 'B0G4TWGTTF', gender: 'M', styleTags: ['formal','minimalist'] },
  { top: 'B0936M17S7', bottom: 'B0G42J6ZC8', gender: 'M', styleTags: ['sporty','streetwear'] },
  { top: 'B0CL79J2MK', bottom: 'B0DPHRDFLN', gender: 'M', styleTags: ['casual','bohemian'] },
  { top: 'B0FY2P2YDT', bottom: 'B0FM8PZQG5', gender: 'M', styleTags: ['casual','minimalist'] },
  { top: 'B0DJQRWH7J', bottom: 'B0F9FF7M4Z', gender: 'M', styleTags: ['casual','minimalist'] },

  // ─── Amazon Unisex Outfits (2) ────────────────────────
  { top: 'B0DJQTQVX5', bottom: 'B0DYJZRHX6', gender: 'U', styleTags: ['casual','formal'] },
  { top: 'B0FY2NZLMN', bottom: 'B0FFB7TK28', gender: 'U', styleTags: ['casual','streetwear'] },

  // ─── SHEIN Women's Outfits (8) ────────────────────────
  { top: '48902379', bottom: '411920692', gender: 'W', styleTags: ['casual','formal'] },
  { top: '42897956', bottom: '73404367', gender: 'W', styleTags: ['casual','sporty'] },
  { top: '147036553', bottom: '91988558', gender: 'W', styleTags: ['casual','minimalist'] },
  { top: '223977591', bottom: '10643526', gender: 'W', styleTags: ['casual','minimalist'] },
  { top: '67665706', bottom: '183214571', gender: 'W', styleTags: ['casual','minimalist'] },
  { top: '31470482', bottom: '200537309', gender: 'W', styleTags: ['casual','formal'] },
  { top: '306124467', bottom: '49233274', gender: 'W', styleTags: ['casual','sporty'] },
  { top: '22131374', bottom: '32258906', gender: 'W', styleTags: ['casual','minimalist'] },

  // ─── SHEIN Men's Outfits (10) ─────────────────────────
  { top: '162986982', bottom: '89109007', gender: 'M', styleTags: ['casual','streetwear'] },
  { top: '58500845', bottom: '207283978', gender: 'M', styleTags: ['casual','streetwear'] },
  { top: '158173353', bottom: '43659610', gender: 'M', styleTags: ['casual','minimalist'] },
  { top: '395384622', bottom: '41187955', gender: 'M', styleTags: ['casual','streetwear'] },
  { top: '153186567', bottom: '150506260', gender: 'M', styleTags: ['casual','minimalist'] },
  { top: '29696334', bottom: '329880153', gender: 'M', styleTags: ['sporty','casual'] },
  { top: '188784152', bottom: '147211871', gender: 'M', styleTags: ['streetwear','casual'] },
  { top: '51905669', bottom: '162746956', gender: 'M', styleTags: ['casual','sporty'] },
  { top: '68766666', bottom: '104032049', gender: 'M', styleTags: ['streetwear','casual'] },
  { top: '280842635', bottom: '64093471', gender: 'M', styleTags: ['casual','streetwear'] },
];
