import { PrismaClient, Platform, Gender } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  // ─── Dresses ───────────────────────────────────────
  // Amazon (4)
  {
    externalId: 'AMZ-DRESS-001',
    platform: Platform.AMAZON,
    name: 'Floral Wrap Midi Dress',
    brand: 'PRETTYGARDEN',
    price: 39.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1614251055880-ee96e4803393?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-dress-001',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['floral', 'casual', 'summer', 'wrap'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'AMZ-DRESS-002',
    platform: Platform.AMAZON,
    name: 'Satin Slip Cocktail Dress',
    brand: 'The Drop',
    price: 54.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-dress-002',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['elegant', 'evening', 'satin', 'minimalist'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'AMZ-DRESS-003',
    platform: Platform.AMAZON,
    name: 'Cotton T-Shirt Dress',
    brand: 'Amazon Essentials',
    price: 22.50,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-dress-003',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    styleTags: ['casual', 'everyday', 'classic', 'cotton'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'AMZ-DRESS-004',
    platform: Platform.AMAZON,
    name: 'Bodycon Ribbed Knit Dress',
    brand: 'Verdusa',
    price: 31.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-dress-004',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['S', 'M', 'L'],
    styleTags: ['trendy', 'bodycon', 'knit', 'streetwear'],
    gender: Gender.FEMALE,
  },
  // SHEIN (5)
  {
    externalId: 'SHN-DRESS-001',
    platform: Platform.SHEIN,
    name: 'Ruched Mesh Bodycon Mini Dress',
    brand: null,
    price: 15.49,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-dress-001',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['trendy', 'bodycon', 'party', 'edgy'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-DRESS-002',
    platform: Platform.SHEIN,
    name: 'Ditsy Floral Puff Sleeve Dress',
    brand: null,
    price: 18.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-dress-002',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['romantic', 'floral', 'boho', 'summer'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-DRESS-003',
    platform: Platform.SHEIN,
    name: 'Solid Cami Maxi Dress',
    brand: null,
    price: 21.00,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-dress-003',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['minimalist', 'casual', 'summer', 'elegant'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-DRESS-004',
    platform: Platform.SHEIN,
    name: 'Plaid Blazer Dress',
    brand: null,
    price: 26.50,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-dress-004',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['S', 'M', 'L'],
    styleTags: ['preppy', 'formal', 'plaid', 'classic'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-DRESS-005',
    platform: Platform.SHEIN,
    name: 'Tie-Dye Oversized T-Shirt Dress',
    brand: null,
    price: 12.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-dress-005',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['streetwear', 'casual', 'oversized', 'trendy'],
    gender: Gender.UNISEX,
  },
  // Zara (4)
  {
    externalId: 'ZRA-DRESS-001',
    platform: Platform.ZARA,
    name: 'Linen Blend Shirt Dress',
    brand: 'Zara',
    price: 69.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1508742345712-0656a285ac27?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-dress-001',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['classic', 'minimalist', 'linen', 'summer'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'ZRA-DRESS-002',
    platform: Platform.ZARA,
    name: 'Asymmetric Knit Midi Dress',
    brand: 'Zara',
    price: 89.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-dress-002',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['S', 'M', 'L'],
    styleTags: ['elegant', 'knit', 'minimalist', 'trendy'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'ZRA-DRESS-003',
    platform: Platform.ZARA,
    name: 'Pleated Satin Evening Dress',
    brand: 'Zara',
    price: 119.00,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-dress-003',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['elegant', 'evening', 'satin', 'formal'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'ZRA-DRESS-004',
    platform: Platform.ZARA,
    name: 'Cut-Out Detail Mini Dress',
    brand: 'Zara',
    price: 59.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1495121605193-b116b5b9c5fe?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-dress-004',
    affiliateUrl: null,
    category: 'dresses',
    fashnCategory: 'one-pieces',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['trendy', 'edgy', 'party', 'summer'],
    gender: Gender.FEMALE,
  },

  // ─── Tops ──────────────────────────────────────────
  // Amazon (5)
  {
    externalId: 'AMZ-TOP-001',
    platform: Platform.AMAZON,
    name: 'Classic Crew Neck T-Shirt',
    brand: 'Amazon Essentials',
    price: 12.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-top-001',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    styleTags: ['casual', 'everyday', 'classic', 'basic'],
    gender: Gender.MALE,
  },
  {
    externalId: 'AMZ-TOP-002',
    platform: Platform.AMAZON,
    name: 'Slim Fit Oxford Button-Down Shirt',
    brand: 'Goodthreads',
    price: 29.50,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-top-002',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['preppy', 'classic', 'formal', 'oxford'],
    gender: Gender.MALE,
  },
  {
    externalId: 'AMZ-TOP-003',
    platform: Platform.AMAZON,
    name: 'Cropped Ribbed Tank Top',
    brand: 'The Drop',
    price: 24.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-top-003',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['casual', 'minimalist', 'summer', 'trendy'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'AMZ-TOP-004',
    platform: Platform.AMAZON,
    name: 'Graphic Print Oversized Hoodie',
    brand: 'Hanes',
    price: 18.00,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-top-004',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    styleTags: ['streetwear', 'casual', 'oversized', 'sporty'],
    gender: Gender.UNISEX,
  },
  {
    externalId: 'AMZ-TOP-005',
    platform: Platform.AMAZON,
    name: 'Lace Trim Camisole',
    brand: 'Verdusa',
    price: 16.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1618453292459-53424b66bb6a?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-top-005',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['romantic', 'elegant', 'lace', 'vintage'],
    gender: Gender.FEMALE,
  },
  // SHEIN (5)
  {
    externalId: 'SHN-TOP-001',
    platform: Platform.SHEIN,
    name: 'Off-Shoulder Ruffle Blouse',
    brand: null,
    price: 13.49,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-top-001',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['romantic', 'boho', 'summer', 'trendy'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-TOP-002',
    platform: Platform.SHEIN,
    name: 'Crop Polo Knit Top',
    brand: null,
    price: 11.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-top-002',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L'],
    styleTags: ['preppy', 'casual', 'knit', 'trendy'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-TOP-003',
    platform: Platform.SHEIN,
    name: 'Letter Print Oversized Tee',
    brand: null,
    price: 8.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-top-003',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['streetwear', 'casual', 'oversized', 'graphic'],
    gender: Gender.UNISEX,
  },
  {
    externalId: 'SHN-TOP-004',
    platform: Platform.SHEIN,
    name: 'Satin Button-Up Shirt',
    brand: null,
    price: 17.50,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-top-004',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L'],
    styleTags: ['elegant', 'satin', 'formal', 'classic'],
    gender: Gender.MALE,
  },
  {
    externalId: 'SHN-TOP-005',
    platform: Platform.SHEIN,
    name: 'Corset Style Bustier Top',
    brand: null,
    price: 19.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-top-005',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['edgy', 'trendy', 'party', 'vintage'],
    gender: Gender.FEMALE,
  },
  // Zara (3)
  {
    externalId: 'ZRA-TOP-001',
    platform: Platform.ZARA,
    name: 'Structured Poplin Blouse',
    brand: 'Zara',
    price: 45.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-top-001',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['classic', 'elegant', 'formal', 'minimalist'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'ZRA-TOP-002',
    platform: Platform.ZARA,
    name: 'Relaxed Fit Linen Shirt',
    brand: 'Zara',
    price: 49.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-top-002',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['casual', 'linen', 'summer', 'minimalist'],
    gender: Gender.MALE,
  },
  {
    externalId: 'ZRA-TOP-003',
    platform: Platform.ZARA,
    name: 'Cashmere Blend V-Neck Sweater',
    brand: 'Zara',
    price: 79.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-top-003',
    affiliateUrl: null,
    category: 'tops',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L'],
    styleTags: ['classic', 'elegant', 'knit', 'minimalist'],
    gender: Gender.UNISEX,
  },

  // ─── Bottoms ───────────────────────────────────────
  // Amazon (4)
  {
    externalId: 'AMZ-BTM-001',
    platform: Platform.AMAZON,
    name: 'High-Waisted Stretch Skinny Jeans',
    brand: 'Levi\'s',
    price: 44.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-btm-001',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['24', '25', '26', '27', '28', '29', '30', '31', '32'],
    styleTags: ['classic', 'everyday', 'denim', 'casual'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'AMZ-BTM-002',
    platform: Platform.AMAZON,
    name: 'Slim Fit Chino Pants',
    brand: 'Amazon Essentials',
    price: 29.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1604176354204-9268737828e4?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-btm-002',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['28', '30', '32', '34', '36'],
    styleTags: ['classic', 'preppy', 'casual', 'versatile'],
    gender: Gender.MALE,
  },
  {
    externalId: 'AMZ-BTM-003',
    platform: Platform.AMAZON,
    name: 'Pleated Wide-Leg Trousers',
    brand: 'The Drop',
    price: 49.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-btm-003',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['elegant', 'classic', 'formal', 'minimalist'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'AMZ-BTM-004',
    platform: Platform.AMAZON,
    name: 'Athletic Jogger Pants',
    brand: 'Champion',
    price: 24.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-btm-004',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    styleTags: ['athleisure', 'sporty', 'casual', 'streetwear'],
    gender: Gender.MALE,
  },
  // SHEIN (4)
  {
    externalId: 'SHN-BTM-001',
    platform: Platform.SHEIN,
    name: 'Cargo Pocket Wide-Leg Pants',
    brand: null,
    price: 22.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-btm-001',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['streetwear', 'trendy', 'cargo', 'casual'],
    gender: Gender.UNISEX,
  },
  {
    externalId: 'SHN-BTM-002',
    platform: Platform.SHEIN,
    name: 'High-Waist Faux Leather Leggings',
    brand: null,
    price: 14.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1551854838-212c50b4c184?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-btm-002',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['edgy', 'trendy', 'streetwear', 'party'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-BTM-003',
    platform: Platform.SHEIN,
    name: 'Pleated Tennis Skirt',
    brand: null,
    price: 11.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-btm-003',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['preppy', 'athleisure', 'sporty', 'trendy'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-BTM-004',
    platform: Platform.SHEIN,
    name: 'Baggy Ripped Boyfriend Jeans',
    brand: null,
    price: 25.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-btm-004',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['streetwear', 'casual', 'denim', 'trendy'],
    gender: Gender.UNISEX,
  },
  // Zara (4)
  {
    externalId: 'ZRA-BTM-001',
    platform: Platform.ZARA,
    name: 'Tailored High-Waist Trousers',
    brand: 'Zara',
    price: 59.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-btm-001',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['formal', 'elegant', 'classic', 'minimalist'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'ZRA-BTM-002',
    platform: Platform.ZARA,
    name: 'Straight Fit Premium Denim Jeans',
    brand: 'Zara',
    price: 49.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-btm-002',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['30', '32', '34', '36'],
    styleTags: ['classic', 'denim', 'casual', 'minimalist'],
    gender: Gender.MALE,
  },
  {
    externalId: 'ZRA-BTM-003',
    platform: Platform.ZARA,
    name: 'Satin Midi Skirt',
    brand: 'Zara',
    price: 45.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-btm-003',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['elegant', 'satin', 'romantic', 'evening'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'ZRA-BTM-004',
    platform: Platform.ZARA,
    name: 'Relaxed Fit Linen Shorts',
    brand: 'Zara',
    price: 35.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-btm-004',
    affiliateUrl: null,
    category: 'bottoms',
    fashnCategory: 'bottoms',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['casual', 'summer', 'linen', 'minimalist'],
    gender: Gender.MALE,
  },

  // ─── Outerwear ─────────────────────────────────────
  // Amazon (4)
  {
    externalId: 'AMZ-OUT-001',
    platform: Platform.AMAZON,
    name: 'Lightweight Packable Puffer Jacket',
    brand: 'Amazon Essentials',
    price: 39.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1548883354-94bcfe321cbb?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-out-001',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    styleTags: ['casual', 'sporty', 'everyday', 'classic'],
    gender: Gender.UNISEX,
  },
  {
    externalId: 'AMZ-OUT-002',
    platform: Platform.AMAZON,
    name: 'Classic Denim Trucker Jacket',
    brand: 'Levi\'s',
    price: 69.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1544441893-675973e31985?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-out-002',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['classic', 'denim', 'casual', 'vintage'],
    gender: Gender.MALE,
  },
  {
    externalId: 'AMZ-OUT-003',
    platform: Platform.AMAZON,
    name: 'Cropped Faux Leather Moto Jacket',
    brand: 'The Drop',
    price: 59.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-out-003',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['edgy', 'streetwear', 'trendy', 'moto'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'AMZ-OUT-004',
    platform: Platform.AMAZON,
    name: 'Fleece-Lined Zip-Up Hoodie',
    brand: 'Carhartt',
    price: 54.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/amz-out-004',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['M', 'L', 'XL', 'XXL'],
    styleTags: ['casual', 'sporty', 'streetwear', 'classic'],
    gender: Gender.MALE,
  },
  // SHEIN (4)
  {
    externalId: 'SHN-OUT-001',
    platform: Platform.SHEIN,
    name: 'Oversized Teddy Bear Coat',
    brand: null,
    price: 34.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1611312449412-6cefac5dc3e4?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-out-001',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['trendy', 'casual', 'oversized', 'boho'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'SHN-OUT-002',
    platform: Platform.SHEIN,
    name: 'Color Block Windbreaker',
    brand: null,
    price: 21.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1591085686350-798c0f9faa7f?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-out-002',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['sporty', 'streetwear', 'athleisure', 'trendy'],
    gender: Gender.UNISEX,
  },
  {
    externalId: 'SHN-OUT-003',
    platform: Platform.SHEIN,
    name: 'Plaid Oversized Shirt Jacket',
    brand: null,
    price: 27.50,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-out-003',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L'],
    styleTags: ['casual', 'plaid', 'vintage', 'streetwear'],
    gender: Gender.UNISEX,
  },
  {
    externalId: 'SHN-OUT-004',
    platform: Platform.SHEIN,
    name: 'Cropped Puffer Vest',
    brand: null,
    price: 18.99,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1616150638538-ffb0679a3fc4?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/shn-out-004',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['trendy', 'sporty', 'casual', 'streetwear'],
    gender: Gender.FEMALE,
  },
  // Zara (4)
  {
    externalId: 'ZRA-OUT-001',
    platform: Platform.ZARA,
    name: 'Wool Blend Double-Breasted Coat',
    brand: 'Zara',
    price: 149.00,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-out-001',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L'],
    styleTags: ['elegant', 'classic', 'formal', 'minimalist'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'ZRA-OUT-002',
    platform: Platform.ZARA,
    name: 'Suede Effect Bomber Jacket',
    brand: 'Zara',
    price: 89.90,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-out-002',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['casual', 'trendy', 'streetwear', 'classic'],
    gender: Gender.MALE,
  },
  {
    externalId: 'ZRA-OUT-003',
    platform: Platform.ZARA,
    name: 'Oversized Blazer with Rolled Sleeves',
    brand: 'Zara',
    price: 109.00,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-out-003',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['classic', 'elegant', 'formal', 'trendy'],
    gender: Gender.FEMALE,
  },
  {
    externalId: 'ZRA-OUT-004',
    platform: Platform.ZARA,
    name: 'Technical Water-Repellent Parka',
    brand: 'Zara',
    price: 129.00,
    currency: 'USD',
    imageUrls: ['https://images.unsplash.com/photo-1608063615781-e2ef8c73d114?w=600&h=900&fit=crop'],
    productPageUrl: 'https://example.com/products/zra-out-004',
    affiliateUrl: null,
    category: 'outerwear',
    fashnCategory: 'tops',
    availableSizes: ['S', 'M', 'L', 'XL'],
    styleTags: ['sporty', 'casual', 'classic', 'athleisure'],
    gender: Gender.MALE,
  },
];

async function main() {
  console.log('Seeding database with 50 curated products...');

  const result = await prisma.product.createMany({
    data: products,
    skipDuplicates: true,
  });

  console.log(`Seeded ${result.count} products successfully.`);
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
